/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CountryV30Rc2,
    CountryV30Rc2FromJSON,
    CountryV30Rc2FromJSONTyped,
    CountryV30Rc2ToJSON,
    CreatedDateV30Rc2,
    CreatedDateV30Rc2FromJSON,
    CreatedDateV30Rc2FromJSONTyped,
    CreatedDateV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    SourceV30Rc2,
    SourceV30Rc2FromJSON,
    SourceV30Rc2FromJSONTyped,
    SourceV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressV30Rc2
 */
export interface AddressV30Rc2 {
    /**
     * 
     * @type {CreatedDateV30Rc2}
     * @memberof AddressV30Rc2
     */
    createdDate?: CreatedDateV30Rc2;
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof AddressV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {SourceV30Rc2}
     * @memberof AddressV30Rc2
     */
    source?: SourceV30Rc2;
    /**
     * 
     * @type {CountryV30Rc2}
     * @memberof AddressV30Rc2
     */
    country: CountryV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof AddressV30Rc2
     */
    visibility?: AddressV30Rc2VisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof AddressV30Rc2
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof AddressV30Rc2
     */
    putCode?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressV30Rc2
     */
    displayIndex?: number;
}

/**
* @export
* @enum {string}
*/
export enum AddressV30Rc2VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function AddressV30Rc2FromJSON(json: any): AddressV30Rc2 {
    return AddressV30Rc2FromJSONTyped(json, false);
}

export function AddressV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30Rc2FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV30Rc2FromJSON(json['source']),
        'country': CountryV30Rc2FromJSON(json['country']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'displayIndex': !exists(json, 'display-index') ? undefined : json['display-index'],
    };
}

export function AddressV30Rc2ToJSON(value?: AddressV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30Rc2ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'source': SourceV30Rc2ToJSON(value.source),
        'country': CountryV30Rc2ToJSON(value.country),
        'visibility': value.visibility,
        'path': value.path,
        'put-code': value.putCode,
        'display-index': value.displayIndex,
    };
}


