/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContributorAttributesV30Rc1
 */
export interface ContributorAttributesV30Rc1 {
    /**
     * 
     * @type {string}
     * @memberof ContributorAttributesV30Rc1
     */
    contributorSequence: ContributorAttributesV30Rc1ContributorSequenceEnum;
    /**
     * 
     * @type {string}
     * @memberof ContributorAttributesV30Rc1
     */
    contributorRole: ContributorAttributesV30Rc1ContributorRoleEnum;
}

/**
* @export
* @enum {string}
*/
export enum ContributorAttributesV30Rc1ContributorSequenceEnum {
    First = 'FIRST',
    Additional = 'ADDITIONAL'
}/**
* @export
* @enum {string}
*/
export enum ContributorAttributesV30Rc1ContributorRoleEnum {
    Author = 'AUTHOR',
    Assignee = 'ASSIGNEE',
    Editor = 'EDITOR',
    ChairOrTranslator = 'CHAIR_OR_TRANSLATOR',
    CoInvestigator = 'CO_INVESTIGATOR',
    CoInventor = 'CO_INVENTOR',
    GraduateStudent = 'GRADUATE_STUDENT',
    OtherInventor = 'OTHER_INVENTOR',
    PrincipalInvestigator = 'PRINCIPAL_INVESTIGATOR',
    PostdoctoralResearcher = 'POSTDOCTORAL_RESEARCHER',
    SupportStaff = 'SUPPORT_STAFF'
}

export function ContributorAttributesV30Rc1FromJSON(json: any): ContributorAttributesV30Rc1 {
    return ContributorAttributesV30Rc1FromJSONTyped(json, false);
}

export function ContributorAttributesV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContributorAttributesV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contributorSequence': json['contributor-sequence'],
        'contributorRole': json['contributor-role'],
    };
}

export function ContributorAttributesV30Rc1ToJSON(value?: ContributorAttributesV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contributor-sequence': value.contributorSequence,
        'contributor-role': value.contributorRole,
    };
}


