/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContributorEmailV20,
    ContributorEmailV20FromJSON,
    ContributorEmailV20FromJSONTyped,
    ContributorEmailV20ToJSON,
    ContributorOrcidV20,
    ContributorOrcidV20FromJSON,
    ContributorOrcidV20FromJSONTyped,
    ContributorOrcidV20ToJSON,
    CreditNameV20,
    CreditNameV20FromJSON,
    CreditNameV20FromJSONTyped,
    CreditNameV20ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ContributorV20
 */
export interface ContributorV20 {
    /**
     * 
     * @type {ContributorOrcidV20}
     * @memberof ContributorV20
     */
    contributorOrcid?: ContributorOrcidV20;
    /**
     * 
     * @type {CreditNameV20}
     * @memberof ContributorV20
     */
    creditName?: CreditNameV20;
    /**
     * 
     * @type {ContributorEmailV20}
     * @memberof ContributorV20
     */
    contributorEmail?: ContributorEmailV20;
    /**
     * 
     * @type {ContributorV20}
     * @memberof ContributorV20
     */
    contributorAttributes?: ContributorV20;
}

export function ContributorV20FromJSON(json: any): ContributorV20 {
    return ContributorV20FromJSONTyped(json, false);
}

export function ContributorV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContributorV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contributorOrcid': !exists(json, 'contributor-orcid') ? undefined : ContributorOrcidV20FromJSON(json['contributor-orcid']),
        'creditName': !exists(json, 'credit-name') ? undefined : CreditNameV20FromJSON(json['credit-name']),
        'contributorEmail': !exists(json, 'contributor-email') ? undefined : ContributorEmailV20FromJSON(json['contributor-email']),
        'contributorAttributes': !exists(json, 'contributor-attributes') ? undefined : ContributorV20FromJSON(json['contributor-attributes']),
    };
}

export function ContributorV20ToJSON(value?: ContributorV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contributor-orcid': ContributorOrcidV20ToJSON(value.contributorOrcid),
        'credit-name': CreditNameV20ToJSON(value.creditName),
        'contributor-email': ContributorEmailV20ToJSON(value.contributorEmail),
        'contributor-attributes': ContributorV20ToJSON(value.contributorAttributes),
    };
}


