/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditNameV30
 */
export interface CreditNameV30 {
    /**
     * 
     * @type {string}
     * @memberof CreditNameV30
     */
    value?: string;
}

export function CreditNameV30FromJSON(json: any): CreditNameV30 {
    return CreditNameV30FromJSONTyped(json, false);
}

export function CreditNameV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditNameV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function CreditNameV30ToJSON(value?: CreditNameV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}


