/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    currencyCode?: string;
    /**
     * 
     * @type {number}
     * @memberof Currency
     */
    defaultFractionDigits?: number;
    /**
     * 
     * @type {number}
     * @memberof Currency
     */
    numericCode?: number;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    symbol?: string;
}

export function CurrencyFromJSON(json: any): Currency {
    return CurrencyFromJSONTyped(json, false);
}

export function CurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Currency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
        'defaultFractionDigits': !exists(json, 'defaultFractionDigits') ? undefined : json['defaultFractionDigits'],
        'numericCode': !exists(json, 'numericCode') ? undefined : json['numericCode'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'symbol': !exists(json, 'symbol') ? undefined : json['symbol'],
    };
}

export function CurrencyToJSON(value?: Currency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencyCode': value.currencyCode,
        'defaultFractionDigits': value.defaultFractionDigits,
        'numericCode': value.numericCode,
        'displayName': value.displayName,
        'symbol': value.symbol,
    };
}


