/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisambiguatedOrganizationV30
 */
export interface DisambiguatedOrganizationV30 {
    /**
     * 
     * @type {string}
     * @memberof DisambiguatedOrganizationV30
     */
    disambiguatedOrganizationIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof DisambiguatedOrganizationV30
     */
    disambiguationSource: string;
}

export function DisambiguatedOrganizationV30FromJSON(json: any): DisambiguatedOrganizationV30 {
    return DisambiguatedOrganizationV30FromJSONTyped(json, false);
}

export function DisambiguatedOrganizationV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): DisambiguatedOrganizationV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disambiguatedOrganizationIdentifier': json['disambiguated-organization-identifier'],
        'disambiguationSource': json['disambiguation-source'],
    };
}

export function DisambiguatedOrganizationV30ToJSON(value?: DisambiguatedOrganizationV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disambiguated-organization-identifier': value.disambiguatedOrganizationIdentifier,
        'disambiguation-source': value.disambiguationSource,
    };
}


