/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AffiliationGroupV30DistinctionSummaryV30,
    AffiliationGroupV30DistinctionSummaryV30FromJSON,
    AffiliationGroupV30DistinctionSummaryV30FromJSONTyped,
    AffiliationGroupV30DistinctionSummaryV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface DistinctionsSummaryV30
 */
export interface DistinctionsSummaryV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof DistinctionsSummaryV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {Array<AffiliationGroupV30DistinctionSummaryV30>}
     * @memberof DistinctionsSummaryV30
     */
    affiliationGroup?: Array<AffiliationGroupV30DistinctionSummaryV30>;
    /**
     * 
     * @type {string}
     * @memberof DistinctionsSummaryV30
     */
    path?: string;
}

export function DistinctionsSummaryV30FromJSON(json: any): DistinctionsSummaryV30 {
    return DistinctionsSummaryV30FromJSONTyped(json, false);
}

export function DistinctionsSummaryV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): DistinctionsSummaryV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'affiliationGroup': !exists(json, 'affiliation-group') ? undefined : ((json['affiliation-group'] as Array<any>).map(AffiliationGroupV30DistinctionSummaryV30FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function DistinctionsSummaryV30ToJSON(value?: DistinctionsSummaryV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'affiliation-group': value.affiliationGroup === undefined ? undefined : ((value.affiliationGroup as Array<any>).map(AffiliationGroupV30DistinctionSummaryV30ToJSON)),
        'path': value.path,
    };
}


