/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AffiliationGroupV30Rc2DistinctionSummaryV30Rc2,
    AffiliationGroupV30Rc2DistinctionSummaryV30Rc2FromJSON,
    AffiliationGroupV30Rc2DistinctionSummaryV30Rc2FromJSONTyped,
    AffiliationGroupV30Rc2DistinctionSummaryV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface DistinctionsSummaryV30Rc2
 */
export interface DistinctionsSummaryV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof DistinctionsSummaryV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {Array<AffiliationGroupV30Rc2DistinctionSummaryV30Rc2>}
     * @memberof DistinctionsSummaryV30Rc2
     */
    affiliationGroup?: Array<AffiliationGroupV30Rc2DistinctionSummaryV30Rc2>;
    /**
     * 
     * @type {string}
     * @memberof DistinctionsSummaryV30Rc2
     */
    path?: string;
}

export function DistinctionsSummaryV30Rc2FromJSON(json: any): DistinctionsSummaryV30Rc2 {
    return DistinctionsSummaryV30Rc2FromJSONTyped(json, false);
}

export function DistinctionsSummaryV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): DistinctionsSummaryV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'affiliationGroup': !exists(json, 'affiliation-group') ? undefined : ((json['affiliation-group'] as Array<any>).map(AffiliationGroupV30Rc2DistinctionSummaryV30Rc2FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function DistinctionsSummaryV30Rc2ToJSON(value?: DistinctionsSummaryV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'affiliation-group': value.affiliationGroup === undefined ? undefined : ((value.affiliationGroup as Array<any>).map(AffiliationGroupV30Rc2DistinctionSummaryV30Rc2ToJSON)),
        'path': value.path,
    };
}


