/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailV20,
    EmailV20FromJSON,
    EmailV20FromJSONTyped,
    EmailV20ToJSON,
    LastModifiedDateV20,
    LastModifiedDateV20FromJSON,
    LastModifiedDateV20FromJSONTyped,
    LastModifiedDateV20ToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmailsV20
 */
export interface EmailsV20 {
    /**
     * 
     * @type {LastModifiedDateV20}
     * @memberof EmailsV20
     */
    lastModifiedDate?: LastModifiedDateV20;
    /**
     * 
     * @type {Array<EmailV20>}
     * @memberof EmailsV20
     */
    email?: Array<EmailV20>;
    /**
     * 
     * @type {string}
     * @memberof EmailsV20
     */
    path?: string;
}

export function EmailsV20FromJSON(json: any): EmailsV20 {
    return EmailsV20FromJSONTyped(json, false);
}

export function EmailsV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailsV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV20FromJSON(json['last-modified-date']),
        'email': !exists(json, 'email') ? undefined : ((json['email'] as Array<any>).map(EmailV20FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function EmailsV20ToJSON(value?: EmailsV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV20ToJSON(value.lastModifiedDate),
        'email': value.email === undefined ? undefined : ((value.email as Array<any>).map(EmailV20ToJSON)),
        'path': value.path,
    };
}


