/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatedDateV30,
    CreatedDateV30FromJSON,
    CreatedDateV30FromJSONTyped,
    CreatedDateV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
    SourceV30,
    SourceV30FromJSON,
    SourceV30FromJSONTyped,
    SourceV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmailV30
 */
export interface EmailV30 {
    /**
     * 
     * @type {CreatedDateV30}
     * @memberof EmailV30
     */
    createdDate?: CreatedDateV30;
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof EmailV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {SourceV30}
     * @memberof EmailV30
     */
    source?: SourceV30;
    /**
     * 
     * @type {string}
     * @memberof EmailV30
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailV30
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailV30
     */
    visibility?: EmailV30VisibilityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EmailV30
     */
    verified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmailV30
     */
    primary?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EmailV30
     */
    putCode?: number;
}

/**
* @export
* @enum {string}
*/
export enum EmailV30VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function EmailV30FromJSON(json: any): EmailV30 {
    return EmailV30FromJSONTyped(json, false);
}

export function EmailV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV30FromJSON(json['source']),
        'email': !exists(json, 'email') ? undefined : json['email'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
        'primary': !exists(json, 'primary') ? undefined : json['primary'],
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
    };
}

export function EmailV30ToJSON(value?: EmailV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'source': SourceV30ToJSON(value.source),
        'email': value.email,
        'path': value.path,
        'visibility': value.visibility,
        'verified': value.verified,
        'primary': value.primary,
        'put-code': value.putCode,
    };
}


