/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatedDateV20,
    CreatedDateV20FromJSON,
    CreatedDateV20FromJSONTyped,
    CreatedDateV20ToJSON,
    FuzzyDateV20,
    FuzzyDateV20FromJSON,
    FuzzyDateV20FromJSONTyped,
    FuzzyDateV20ToJSON,
    LastModifiedDateV20,
    LastModifiedDateV20FromJSON,
    LastModifiedDateV20FromJSONTyped,
    LastModifiedDateV20ToJSON,
    OrganizationV20,
    OrganizationV20FromJSON,
    OrganizationV20FromJSONTyped,
    OrganizationV20ToJSON,
    SourceV20,
    SourceV20FromJSON,
    SourceV20FromJSONTyped,
    SourceV20ToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmploymentV20
 */
export interface EmploymentV20 {
    /**
     * 
     * @type {CreatedDateV20}
     * @memberof EmploymentV20
     */
    createdDate?: CreatedDateV20;
    /**
     * 
     * @type {LastModifiedDateV20}
     * @memberof EmploymentV20
     */
    lastModifiedDate?: LastModifiedDateV20;
    /**
     * 
     * @type {SourceV20}
     * @memberof EmploymentV20
     */
    source?: SourceV20;
    /**
     * 
     * @type {number}
     * @memberof EmploymentV20
     */
    putCode?: number;
    /**
     * 
     * @type {string}
     * @memberof EmploymentV20
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof EmploymentV20
     */
    departmentName?: string;
    /**
     * 
     * @type {string}
     * @memberof EmploymentV20
     */
    roleTitle?: string;
    /**
     * 
     * @type {FuzzyDateV20}
     * @memberof EmploymentV20
     */
    startDate?: FuzzyDateV20;
    /**
     * 
     * @type {FuzzyDateV20}
     * @memberof EmploymentV20
     */
    endDate?: FuzzyDateV20;
    /**
     * 
     * @type {OrganizationV20}
     * @memberof EmploymentV20
     */
    organization: OrganizationV20;
    /**
     * 
     * @type {string}
     * @memberof EmploymentV20
     */
    visibility?: EmploymentV20VisibilityEnum;
}

/**
* @export
* @enum {string}
*/
export enum EmploymentV20VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function EmploymentV20FromJSON(json: any): EmploymentV20 {
    return EmploymentV20FromJSONTyped(json, false);
}

export function EmploymentV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): EmploymentV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV20FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV20FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV20FromJSON(json['source']),
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'departmentName': !exists(json, 'department-name') ? undefined : json['department-name'],
        'roleTitle': !exists(json, 'role-title') ? undefined : json['role-title'],
        'startDate': !exists(json, 'start-date') ? undefined : FuzzyDateV20FromJSON(json['start-date']),
        'endDate': !exists(json, 'end-date') ? undefined : FuzzyDateV20FromJSON(json['end-date']),
        'organization': OrganizationV20FromJSON(json['organization']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
    };
}

export function EmploymentV20ToJSON(value?: EmploymentV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV20ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV20ToJSON(value.lastModifiedDate),
        'source': SourceV20ToJSON(value.source),
        'put-code': value.putCode,
        'path': value.path,
        'department-name': value.departmentName,
        'role-title': value.roleTitle,
        'start-date': FuzzyDateV20ToJSON(value.startDate),
        'end-date': FuzzyDateV20ToJSON(value.endDate),
        'organization': OrganizationV20ToJSON(value.organization),
        'visibility': value.visibility,
    };
}


