/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDV20,
    ExternalIDV20FromJSON,
    ExternalIDV20FromJSONTyped,
    ExternalIDV20ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExternalIDsV20
 */
export interface ExternalIDsV20 {
    /**
     * 
     * @type {Array<ExternalIDV20>}
     * @memberof ExternalIDsV20
     */
    externalId?: Array<ExternalIDV20>;
}

export function ExternalIDsV20FromJSON(json: any): ExternalIDsV20 {
    return ExternalIDsV20FromJSONTyped(json, false);
}

export function ExternalIDsV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalIDsV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalId': !exists(json, 'external-id') ? undefined : ((json['external-id'] as Array<any>).map(ExternalIDV20FromJSON)),
    };
}

export function ExternalIDsV20ToJSON(value?: ExternalIDsV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external-id': value.externalId === undefined ? undefined : ((value.externalId as Array<any>).map(ExternalIDV20ToJSON)),
    };
}


