/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30Rc1,
    ExternalIDsV30Rc1FromJSON,
    ExternalIDsV30Rc1FromJSONTyped,
    ExternalIDsV30Rc1ToJSON,
    FundingSummaryV30Rc1,
    FundingSummaryV30Rc1FromJSON,
    FundingSummaryV30Rc1FromJSONTyped,
    FundingSummaryV30Rc1ToJSON,
    LastModifiedDateV30Rc1,
    LastModifiedDateV30Rc1FromJSON,
    LastModifiedDateV30Rc1FromJSONTyped,
    LastModifiedDateV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface FundingGroupV30Rc1
 */
export interface FundingGroupV30Rc1 {
    /**
     * 
     * @type {LastModifiedDateV30Rc1}
     * @memberof FundingGroupV30Rc1
     */
    lastModifiedDate?: LastModifiedDateV30Rc1;
    /**
     * 
     * @type {ExternalIDsV30Rc1}
     * @memberof FundingGroupV30Rc1
     */
    externalIds?: ExternalIDsV30Rc1;
    /**
     * 
     * @type {Array<FundingSummaryV30Rc1>}
     * @memberof FundingGroupV30Rc1
     */
    fundingSummary?: Array<FundingSummaryV30Rc1>;
}

export function FundingGroupV30Rc1FromJSON(json: any): FundingGroupV30Rc1 {
    return FundingGroupV30Rc1FromJSONTyped(json, false);
}

export function FundingGroupV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingGroupV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc1FromJSON(json['last-modified-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30Rc1FromJSON(json['external-ids']),
        'fundingSummary': !exists(json, 'funding-summary') ? undefined : ((json['funding-summary'] as Array<any>).map(FundingSummaryV30Rc1FromJSON)),
    };
}

export function FundingGroupV30Rc1ToJSON(value?: FundingGroupV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc1ToJSON(value.lastModifiedDate),
        'external-ids': ExternalIDsV30Rc1ToJSON(value.externalIds),
        'funding-summary': value.fundingSummary === undefined ? undefined : ((value.fundingSummary as Array<any>).map(FundingSummaryV30Rc1ToJSON)),
    };
}


