/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TitleV30Rc2,
    TitleV30Rc2FromJSON,
    TitleV30Rc2FromJSONTyped,
    TitleV30Rc2ToJSON,
    TranslatedTitleV30Rc2,
    TranslatedTitleV30Rc2FromJSON,
    TranslatedTitleV30Rc2FromJSONTyped,
    TranslatedTitleV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface FundingTitleV30Rc2
 */
export interface FundingTitleV30Rc2 {
    /**
     * 
     * @type {TitleV30Rc2}
     * @memberof FundingTitleV30Rc2
     */
    title?: TitleV30Rc2;
    /**
     * 
     * @type {TranslatedTitleV30Rc2}
     * @memberof FundingTitleV30Rc2
     */
    translatedTitle?: TranslatedTitleV30Rc2;
}

export function FundingTitleV30Rc2FromJSON(json: any): FundingTitleV30Rc2 {
    return FundingTitleV30Rc2FromJSONTyped(json, false);
}

export function FundingTitleV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingTitleV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : TitleV30Rc2FromJSON(json['title']),
        'translatedTitle': !exists(json, 'translated-title') ? undefined : TranslatedTitleV30Rc2FromJSON(json['translated-title']),
    };
}

export function FundingTitleV30Rc2ToJSON(value?: FundingTitleV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': TitleV30Rc2ToJSON(value.title),
        'translated-title': TranslatedTitleV30Rc2ToJSON(value.translatedTitle),
    };
}


