/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FundingContributorV30Rc1,
    FundingContributorV30Rc1FromJSON,
    FundingContributorV30Rc1FromJSONTyped,
    FundingContributorV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface FundingContributorsV30Rc1
 */
export interface FundingContributorsV30Rc1 {
    /**
     * 
     * @type {Array<FundingContributorV30Rc1>}
     * @memberof FundingContributorsV30Rc1
     */
    contributor?: Array<FundingContributorV30Rc1>;
}

export function FundingContributorsV30Rc1FromJSON(json: any): FundingContributorsV30Rc1 {
    return FundingContributorsV30Rc1FromJSONTyped(json, false);
}

export function FundingContributorsV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingContributorsV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contributor': !exists(json, 'contributor') ? undefined : ((json['contributor'] as Array<any>).map(FundingContributorV30Rc1FromJSON)),
    };
}

export function FundingContributorsV30Rc1ToJSON(value?: FundingContributorsV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contributor': value.contributor === undefined ? undefined : ((value.contributor as Array<any>).map(FundingContributorV30Rc1ToJSON)),
    };
}


