/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AmountV30,
    AmountV30FromJSON,
    AmountV30FromJSONTyped,
    AmountV30ToJSON,
    CreatedDateV30,
    CreatedDateV30FromJSON,
    CreatedDateV30FromJSONTyped,
    CreatedDateV30ToJSON,
    ExternalIDsV30,
    ExternalIDsV30FromJSON,
    ExternalIDsV30FromJSONTyped,
    ExternalIDsV30ToJSON,
    FundingContributorsV30,
    FundingContributorsV30FromJSON,
    FundingContributorsV30FromJSONTyped,
    FundingContributorsV30ToJSON,
    FundingTitleV30,
    FundingTitleV30FromJSON,
    FundingTitleV30FromJSONTyped,
    FundingTitleV30ToJSON,
    FuzzyDateV30,
    FuzzyDateV30FromJSON,
    FuzzyDateV30FromJSONTyped,
    FuzzyDateV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
    OrganizationDefinedFundingSubTypeV30,
    OrganizationDefinedFundingSubTypeV30FromJSON,
    OrganizationDefinedFundingSubTypeV30FromJSONTyped,
    OrganizationDefinedFundingSubTypeV30ToJSON,
    OrganizationV30,
    OrganizationV30FromJSON,
    OrganizationV30FromJSONTyped,
    OrganizationV30ToJSON,
    SourceV30,
    SourceV30FromJSON,
    SourceV30FromJSONTyped,
    SourceV30ToJSON,
    UrlV30,
    UrlV30FromJSON,
    UrlV30FromJSONTyped,
    UrlV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface FundingV30
 */
export interface FundingV30 {
    /**
     * 
     * @type {CreatedDateV30}
     * @memberof FundingV30
     */
    createdDate?: CreatedDateV30;
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof FundingV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {SourceV30}
     * @memberof FundingV30
     */
    source?: SourceV30;
    /**
     * 
     * @type {number}
     * @memberof FundingV30
     */
    putCode?: number;
    /**
     * 
     * @type {string}
     * @memberof FundingV30
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingV30
     */
    type: FundingV30TypeEnum;
    /**
     * 
     * @type {OrganizationDefinedFundingSubTypeV30}
     * @memberof FundingV30
     */
    organizationDefinedType?: OrganizationDefinedFundingSubTypeV30;
    /**
     * 
     * @type {FundingTitleV30}
     * @memberof FundingV30
     */
    title: FundingTitleV30;
    /**
     * 
     * @type {string}
     * @memberof FundingV30
     */
    shortDescription?: string;
    /**
     * 
     * @type {AmountV30}
     * @memberof FundingV30
     */
    amount?: AmountV30;
    /**
     * 
     * @type {UrlV30}
     * @memberof FundingV30
     */
    url?: UrlV30;
    /**
     * 
     * @type {FuzzyDateV30}
     * @memberof FundingV30
     */
    startDate?: FuzzyDateV30;
    /**
     * 
     * @type {FuzzyDateV30}
     * @memberof FundingV30
     */
    endDate?: FuzzyDateV30;
    /**
     * 
     * @type {ExternalIDsV30}
     * @memberof FundingV30
     */
    externalIds?: ExternalIDsV30;
    /**
     * 
     * @type {FundingContributorsV30}
     * @memberof FundingV30
     */
    contributors?: FundingContributorsV30;
    /**
     * 
     * @type {OrganizationV30}
     * @memberof FundingV30
     */
    organization: OrganizationV30;
    /**
     * 
     * @type {string}
     * @memberof FundingV30
     */
    visibility?: FundingV30VisibilityEnum;
}

/**
* @export
* @enum {string}
*/
export enum FundingV30TypeEnum {
    Grant = 'grant',
    Contract = 'contract',
    Award = 'award',
    SalaryAward = 'salary-award'
}/**
* @export
* @enum {string}
*/
export enum FundingV30VisibilityEnum {
    Limited = 'limited',
    RegisteredOnly = 'registered-only',
    Public = 'public'
}

export function FundingV30FromJSON(json: any): FundingV30 {
    return FundingV30FromJSONTyped(json, false);
}

export function FundingV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV30FromJSON(json['source']),
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'type': json['type'],
        'organizationDefinedType': !exists(json, 'organization-defined-type') ? undefined : OrganizationDefinedFundingSubTypeV30FromJSON(json['organization-defined-type']),
        'title': FundingTitleV30FromJSON(json['title']),
        'shortDescription': !exists(json, 'short-description') ? undefined : json['short-description'],
        'amount': !exists(json, 'amount') ? undefined : AmountV30FromJSON(json['amount']),
        'url': !exists(json, 'url') ? undefined : UrlV30FromJSON(json['url']),
        'startDate': !exists(json, 'start-date') ? undefined : FuzzyDateV30FromJSON(json['start-date']),
        'endDate': !exists(json, 'end-date') ? undefined : FuzzyDateV30FromJSON(json['end-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30FromJSON(json['external-ids']),
        'contributors': !exists(json, 'contributors') ? undefined : FundingContributorsV30FromJSON(json['contributors']),
        'organization': OrganizationV30FromJSON(json['organization']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
    };
}

export function FundingV30ToJSON(value?: FundingV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'source': SourceV30ToJSON(value.source),
        'put-code': value.putCode,
        'path': value.path,
        'type': value.type,
        'organization-defined-type': OrganizationDefinedFundingSubTypeV30ToJSON(value.organizationDefinedType),
        'title': FundingTitleV30ToJSON(value.title),
        'short-description': value.shortDescription,
        'amount': AmountV30ToJSON(value.amount),
        'url': UrlV30ToJSON(value.url),
        'start-date': FuzzyDateV30ToJSON(value.startDate),
        'end-date': FuzzyDateV30ToJSON(value.endDate),
        'external-ids': ExternalIDsV30ToJSON(value.externalIds),
        'contributors': FundingContributorsV30ToJSON(value.contributors),
        'organization': OrganizationV30ToJSON(value.organization),
        'visibility': value.visibility,
    };
}


