/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FundingGroupV30,
    FundingGroupV30FromJSON,
    FundingGroupV30FromJSONTyped,
    FundingGroupV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface FundingsV30
 */
export interface FundingsV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof FundingsV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {Array<FundingGroupV30>}
     * @memberof FundingsV30
     */
    group?: Array<FundingGroupV30>;
    /**
     * 
     * @type {string}
     * @memberof FundingsV30
     */
    path?: string;
}

export function FundingsV30FromJSON(json: any): FundingsV30 {
    return FundingsV30FromJSONTyped(json, false);
}

export function FundingsV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingsV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'group': !exists(json, 'group') ? undefined : ((json['group'] as Array<any>).map(FundingGroupV30FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function FundingsV30ToJSON(value?: FundingsV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'group': value.group === undefined ? undefined : ((value.group as Array<any>).map(FundingGroupV30ToJSON)),
        'path': value.path,
    };
}


