/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompletionDateV30,
    CompletionDateV30FromJSON,
    CompletionDateV30FromJSONTyped,
    CompletionDateV30ToJSON,
    DeactivationDateV30,
    DeactivationDateV30FromJSON,
    DeactivationDateV30FromJSONTyped,
    DeactivationDateV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
    SourceV30,
    SourceV30FromJSON,
    SourceV30FromJSONTyped,
    SourceV30ToJSON,
    SubmissionDateV30,
    SubmissionDateV30FromJSON,
    SubmissionDateV30FromJSONTyped,
    SubmissionDateV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface HistoryV30
 */
export interface HistoryV30 {
    /**
     * 
     * @type {string}
     * @memberof HistoryV30
     */
    creationMethod?: HistoryV30CreationMethodEnum;
    /**
     * 
     * @type {CompletionDateV30}
     * @memberof HistoryV30
     */
    completionDate?: CompletionDateV30;
    /**
     * 
     * @type {SubmissionDateV30}
     * @memberof HistoryV30
     */
    submissionDate?: SubmissionDateV30;
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof HistoryV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30
     */
    claimed?: boolean;
    /**
     * 
     * @type {SourceV30}
     * @memberof HistoryV30
     */
    source?: SourceV30;
    /**
     * 
     * @type {DeactivationDateV30}
     * @memberof HistoryV30
     */
    deactivationDate?: DeactivationDateV30;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30
     */
    verifiedEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30
     */
    verifiedPrimaryEmail?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum HistoryV30CreationMethodEnum {
    Api = 'API',
    Direct = 'DIRECT',
    MemberReferred = 'MEMBER_REFERRED',
    Website = 'WEBSITE',
    IntegrationTest = 'INTEGRATION_TEST'
}

export function HistoryV30FromJSON(json: any): HistoryV30 {
    return HistoryV30FromJSONTyped(json, false);
}

export function HistoryV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creationMethod': !exists(json, 'creation-method') ? undefined : json['creation-method'],
        'completionDate': !exists(json, 'completion-date') ? undefined : CompletionDateV30FromJSON(json['completion-date']),
        'submissionDate': !exists(json, 'submission-date') ? undefined : SubmissionDateV30FromJSON(json['submission-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'claimed': !exists(json, 'claimed') ? undefined : json['claimed'],
        'source': !exists(json, 'source') ? undefined : SourceV30FromJSON(json['source']),
        'deactivationDate': !exists(json, 'deactivation-date') ? undefined : DeactivationDateV30FromJSON(json['deactivation-date']),
        'verifiedEmail': !exists(json, 'verified-email') ? undefined : json['verified-email'],
        'verifiedPrimaryEmail': !exists(json, 'verified-primary-email') ? undefined : json['verified-primary-email'],
    };
}

export function HistoryV30ToJSON(value?: HistoryV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creation-method': value.creationMethod,
        'completion-date': CompletionDateV30ToJSON(value.completionDate),
        'submission-date': SubmissionDateV30ToJSON(value.submissionDate),
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'claimed': value.claimed,
        'source': SourceV30ToJSON(value.source),
        'deactivation-date': DeactivationDateV30ToJSON(value.deactivationDate),
        'verified-email': value.verifiedEmail,
        'verified-primary-email': value.verifiedPrimaryEmail,
    };
}


