/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompletionDateV30Rc2,
    CompletionDateV30Rc2FromJSON,
    CompletionDateV30Rc2FromJSONTyped,
    CompletionDateV30Rc2ToJSON,
    DeactivationDateV30Rc2,
    DeactivationDateV30Rc2FromJSON,
    DeactivationDateV30Rc2FromJSONTyped,
    DeactivationDateV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    SourceV30Rc2,
    SourceV30Rc2FromJSON,
    SourceV30Rc2FromJSONTyped,
    SourceV30Rc2ToJSON,
    SubmissionDateV30Rc2,
    SubmissionDateV30Rc2FromJSON,
    SubmissionDateV30Rc2FromJSONTyped,
    SubmissionDateV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface HistoryV30Rc2
 */
export interface HistoryV30Rc2 {
    /**
     * 
     * @type {string}
     * @memberof HistoryV30Rc2
     */
    creationMethod?: HistoryV30Rc2CreationMethodEnum;
    /**
     * 
     * @type {CompletionDateV30Rc2}
     * @memberof HistoryV30Rc2
     */
    completionDate?: CompletionDateV30Rc2;
    /**
     * 
     * @type {SubmissionDateV30Rc2}
     * @memberof HistoryV30Rc2
     */
    submissionDate?: SubmissionDateV30Rc2;
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof HistoryV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30Rc2
     */
    claimed?: boolean;
    /**
     * 
     * @type {SourceV30Rc2}
     * @memberof HistoryV30Rc2
     */
    source?: SourceV30Rc2;
    /**
     * 
     * @type {DeactivationDateV30Rc2}
     * @memberof HistoryV30Rc2
     */
    deactivationDate?: DeactivationDateV30Rc2;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30Rc2
     */
    verifiedEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryV30Rc2
     */
    verifiedPrimaryEmail?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum HistoryV30Rc2CreationMethodEnum {
    Api = 'API',
    Direct = 'DIRECT',
    MemberReferred = 'MEMBER_REFERRED',
    Website = 'WEBSITE',
    IntegrationTest = 'INTEGRATION_TEST'
}

export function HistoryV30Rc2FromJSON(json: any): HistoryV30Rc2 {
    return HistoryV30Rc2FromJSONTyped(json, false);
}

export function HistoryV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creationMethod': !exists(json, 'creation-method') ? undefined : json['creation-method'],
        'completionDate': !exists(json, 'completion-date') ? undefined : CompletionDateV30Rc2FromJSON(json['completion-date']),
        'submissionDate': !exists(json, 'submission-date') ? undefined : SubmissionDateV30Rc2FromJSON(json['submission-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'claimed': !exists(json, 'claimed') ? undefined : json['claimed'],
        'source': !exists(json, 'source') ? undefined : SourceV30Rc2FromJSON(json['source']),
        'deactivationDate': !exists(json, 'deactivation-date') ? undefined : DeactivationDateV30Rc2FromJSON(json['deactivation-date']),
        'verifiedEmail': !exists(json, 'verified-email') ? undefined : json['verified-email'],
        'verifiedPrimaryEmail': !exists(json, 'verified-primary-email') ? undefined : json['verified-primary-email'],
    };
}

export function HistoryV30Rc2ToJSON(value?: HistoryV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creation-method': value.creationMethod,
        'completion-date': CompletionDateV30Rc2ToJSON(value.completionDate),
        'submission-date': SubmissionDateV30Rc2ToJSON(value.submissionDate),
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'claimed': value.claimed,
        'source': SourceV30Rc2ToJSON(value.source),
        'deactivation-date': DeactivationDateV30Rc2ToJSON(value.deactivationDate),
        'verified-email': value.verifiedEmail,
        'verified-primary-email': value.verifiedPrimaryEmail,
    };
}


