/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KeywordV30Rc2,
    KeywordV30Rc2FromJSON,
    KeywordV30Rc2FromJSONTyped,
    KeywordV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface KeywordsV30Rc2
 */
export interface KeywordsV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof KeywordsV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {Array<KeywordV30Rc2>}
     * @memberof KeywordsV30Rc2
     */
    keyword?: Array<KeywordV30Rc2>;
    /**
     * 
     * @type {string}
     * @memberof KeywordsV30Rc2
     */
    path?: string;
}

export function KeywordsV30Rc2FromJSON(json: any): KeywordsV30Rc2 {
    return KeywordsV30Rc2FromJSONTyped(json, false);
}

export function KeywordsV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): KeywordsV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'keyword': !exists(json, 'keyword') ? undefined : ((json['keyword'] as Array<any>).map(KeywordV30Rc2FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function KeywordsV30Rc2ToJSON(value?: KeywordsV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'keyword': value.keyword === undefined ? undefined : ((value.keyword as Array<any>).map(KeywordV30Rc2ToJSON)),
        'path': value.path,
    };
}


