/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KeywordV30,
    KeywordV30FromJSON,
    KeywordV30FromJSONTyped,
    KeywordV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface KeywordsV30
 */
export interface KeywordsV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof KeywordsV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {Array<KeywordV30>}
     * @memberof KeywordsV30
     */
    keyword?: Array<KeywordV30>;
    /**
     * 
     * @type {string}
     * @memberof KeywordsV30
     */
    path?: string;
}

export function KeywordsV30FromJSON(json: any): KeywordsV30 {
    return KeywordsV30FromJSONTyped(json, false);
}

export function KeywordsV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): KeywordsV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'keyword': !exists(json, 'keyword') ? undefined : ((json['keyword'] as Array<any>).map(KeywordV30FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function KeywordsV30ToJSON(value?: KeywordsV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'keyword': value.keyword === undefined ? undefined : ((value.keyword as Array<any>).map(KeywordV30ToJSON)),
        'path': value.path,
    };
}


