/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatedDateV30Rc2,
    CreatedDateV30Rc2FromJSON,
    CreatedDateV30Rc2FromJSONTyped,
    CreatedDateV30Rc2ToJSON,
    CreditNameV30Rc2,
    CreditNameV30Rc2FromJSON,
    CreditNameV30Rc2FromJSONTyped,
    CreditNameV30Rc2ToJSON,
    FamilyNameV30Rc2,
    FamilyNameV30Rc2FromJSON,
    FamilyNameV30Rc2FromJSONTyped,
    FamilyNameV30Rc2ToJSON,
    GivenNamesV30Rc2,
    GivenNamesV30Rc2FromJSON,
    GivenNamesV30Rc2FromJSONTyped,
    GivenNamesV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    SourceV30Rc2,
    SourceV30Rc2FromJSON,
    SourceV30Rc2FromJSONTyped,
    SourceV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface NameV30Rc2
 */
export interface NameV30Rc2 {
    /**
     * 
     * @type {CreatedDateV30Rc2}
     * @memberof NameV30Rc2
     */
    createdDate?: CreatedDateV30Rc2;
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof NameV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {GivenNamesV30Rc2}
     * @memberof NameV30Rc2
     */
    givenNames?: GivenNamesV30Rc2;
    /**
     * 
     * @type {FamilyNameV30Rc2}
     * @memberof NameV30Rc2
     */
    familyName?: FamilyNameV30Rc2;
    /**
     * 
     * @type {CreditNameV30Rc2}
     * @memberof NameV30Rc2
     */
    creditName?: CreditNameV30Rc2;
    /**
     * 
     * @type {SourceV30Rc2}
     * @memberof NameV30Rc2
     */
    source?: SourceV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof NameV30Rc2
     */
    visibility?: NameV30Rc2VisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof NameV30Rc2
     */
    path?: string;
}

/**
* @export
* @enum {string}
*/
export enum NameV30Rc2VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function NameV30Rc2FromJSON(json: any): NameV30Rc2 {
    return NameV30Rc2FromJSONTyped(json, false);
}

export function NameV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NameV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30Rc2FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'givenNames': !exists(json, 'given-names') ? undefined : GivenNamesV30Rc2FromJSON(json['given-names']),
        'familyName': !exists(json, 'family-name') ? undefined : FamilyNameV30Rc2FromJSON(json['family-name']),
        'creditName': !exists(json, 'credit-name') ? undefined : CreditNameV30Rc2FromJSON(json['credit-name']),
        'source': !exists(json, 'source') ? undefined : SourceV30Rc2FromJSON(json['source']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function NameV30Rc2ToJSON(value?: NameV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30Rc2ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'given-names': GivenNamesV30Rc2ToJSON(value.givenNames),
        'family-name': FamilyNameV30Rc2ToJSON(value.familyName),
        'credit-name': CreditNameV30Rc2ToJSON(value.creditName),
        'source': SourceV30Rc2ToJSON(value.source),
        'visibility': value.visibility,
        'path': value.path,
    };
}


