/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30Rc1,
    ExternalIDsV30Rc1FromJSON,
    ExternalIDsV30Rc1FromJSONTyped,
    ExternalIDsV30Rc1ToJSON,
    LastModifiedDateV30Rc1,
    LastModifiedDateV30Rc1FromJSON,
    LastModifiedDateV30Rc1FromJSONTyped,
    LastModifiedDateV30Rc1ToJSON,
    PeerReviewSummaryV30Rc1,
    PeerReviewSummaryV30Rc1FromJSON,
    PeerReviewSummaryV30Rc1FromJSONTyped,
    PeerReviewSummaryV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PeerReviewDuplicateGroupV30Rc1
 */
export interface PeerReviewDuplicateGroupV30Rc1 {
    /**
     * 
     * @type {LastModifiedDateV30Rc1}
     * @memberof PeerReviewDuplicateGroupV30Rc1
     */
    lastModifiedDate?: LastModifiedDateV30Rc1;
    /**
     * 
     * @type {ExternalIDsV30Rc1}
     * @memberof PeerReviewDuplicateGroupV30Rc1
     */
    externalIds?: ExternalIDsV30Rc1;
    /**
     * 
     * @type {Array<PeerReviewSummaryV30Rc1>}
     * @memberof PeerReviewDuplicateGroupV30Rc1
     */
    peerReviewSummary?: Array<PeerReviewSummaryV30Rc1>;
}

export function PeerReviewDuplicateGroupV30Rc1FromJSON(json: any): PeerReviewDuplicateGroupV30Rc1 {
    return PeerReviewDuplicateGroupV30Rc1FromJSONTyped(json, false);
}

export function PeerReviewDuplicateGroupV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PeerReviewDuplicateGroupV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc1FromJSON(json['last-modified-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30Rc1FromJSON(json['external-ids']),
        'peerReviewSummary': !exists(json, 'peer-review-summary') ? undefined : ((json['peer-review-summary'] as Array<any>).map(PeerReviewSummaryV30Rc1FromJSON)),
    };
}

export function PeerReviewDuplicateGroupV30Rc1ToJSON(value?: PeerReviewDuplicateGroupV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc1ToJSON(value.lastModifiedDate),
        'external-ids': ExternalIDsV30Rc1ToJSON(value.externalIds),
        'peer-review-summary': value.peerReviewSummary === undefined ? undefined : ((value.peerReviewSummary as Array<any>).map(PeerReviewSummaryV30Rc1ToJSON)),
    };
}


