/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatedDateV30Rc2,
    CreatedDateV30Rc2FromJSON,
    CreatedDateV30Rc2FromJSONTyped,
    CreatedDateV30Rc2ToJSON,
    ExternalIDsV30Rc2,
    ExternalIDsV30Rc2FromJSON,
    ExternalIDsV30Rc2FromJSONTyped,
    ExternalIDsV30Rc2ToJSON,
    FuzzyDateV30Rc2,
    FuzzyDateV30Rc2FromJSON,
    FuzzyDateV30Rc2FromJSONTyped,
    FuzzyDateV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    OrganizationV30Rc2,
    OrganizationV30Rc2FromJSON,
    OrganizationV30Rc2FromJSONTyped,
    OrganizationV30Rc2ToJSON,
    SourceV30Rc2,
    SourceV30Rc2FromJSON,
    SourceV30Rc2FromJSONTyped,
    SourceV30Rc2ToJSON,
    UrlV30Rc2,
    UrlV30Rc2FromJSON,
    UrlV30Rc2FromJSONTyped,
    UrlV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PeerReviewSummaryV30Rc2
 */
export interface PeerReviewSummaryV30Rc2 {
    /**
     * 
     * @type {CreatedDateV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    createdDate?: CreatedDateV30Rc2;
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {SourceV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    source?: SourceV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    reviewerRole?: PeerReviewSummaryV30Rc2ReviewerRoleEnum;
    /**
     * 
     * @type {ExternalIDsV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    externalIds?: ExternalIDsV30Rc2;
    /**
     * 
     * @type {UrlV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    reviewUrl?: UrlV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    reviewType?: PeerReviewSummaryV30Rc2ReviewTypeEnum;
    /**
     * 
     * @type {FuzzyDateV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    completionDate?: FuzzyDateV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    reviewGroupId: string;
    /**
     * 
     * @type {OrganizationV30Rc2}
     * @memberof PeerReviewSummaryV30Rc2
     */
    conveningOrganization: OrganizationV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    visibility?: PeerReviewSummaryV30Rc2VisibilityEnum;
    /**
     * 
     * @type {number}
     * @memberof PeerReviewSummaryV30Rc2
     */
    putCode?: number;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof PeerReviewSummaryV30Rc2
     */
    displayIndex?: string;
}

/**
* @export
* @enum {string}
*/
export enum PeerReviewSummaryV30Rc2ReviewerRoleEnum {
    Reviewer = 'REVIEWER',
    Editor = 'EDITOR',
    Member = 'MEMBER',
    Chair = 'CHAIR',
    Organizer = 'ORGANIZER'
}/**
* @export
* @enum {string}
*/
export enum PeerReviewSummaryV30Rc2ReviewTypeEnum {
    Review = 'REVIEW',
    Evaluation = 'EVALUATION'
}/**
* @export
* @enum {string}
*/
export enum PeerReviewSummaryV30Rc2VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function PeerReviewSummaryV30Rc2FromJSON(json: any): PeerReviewSummaryV30Rc2 {
    return PeerReviewSummaryV30Rc2FromJSONTyped(json, false);
}

export function PeerReviewSummaryV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PeerReviewSummaryV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30Rc2FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV30Rc2FromJSON(json['source']),
        'reviewerRole': !exists(json, 'reviewer-role') ? undefined : json['reviewer-role'],
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30Rc2FromJSON(json['external-ids']),
        'reviewUrl': !exists(json, 'review-url') ? undefined : UrlV30Rc2FromJSON(json['review-url']),
        'reviewType': !exists(json, 'review-type') ? undefined : json['review-type'],
        'completionDate': !exists(json, 'completion-date') ? undefined : FuzzyDateV30Rc2FromJSON(json['completion-date']),
        'reviewGroupId': json['review-group-id'],
        'conveningOrganization': OrganizationV30Rc2FromJSON(json['convening-organization']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'displayIndex': !exists(json, 'display-index') ? undefined : json['display-index'],
    };
}

export function PeerReviewSummaryV30Rc2ToJSON(value?: PeerReviewSummaryV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30Rc2ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'source': SourceV30Rc2ToJSON(value.source),
        'reviewer-role': value.reviewerRole,
        'external-ids': ExternalIDsV30Rc2ToJSON(value.externalIds),
        'review-url': UrlV30Rc2ToJSON(value.reviewUrl),
        'review-type': value.reviewType,
        'completion-date': FuzzyDateV30Rc2ToJSON(value.completionDate),
        'review-group-id': value.reviewGroupId,
        'convening-organization': OrganizationV30Rc2ToJSON(value.conveningOrganization),
        'visibility': value.visibility,
        'put-code': value.putCode,
        'path': value.path,
        'display-index': value.displayIndex,
    };
}


