/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressesV30Rc1,
    AddressesV30Rc1FromJSON,
    AddressesV30Rc1FromJSONTyped,
    AddressesV30Rc1ToJSON,
    BiographyV30Rc1,
    BiographyV30Rc1FromJSON,
    BiographyV30Rc1FromJSONTyped,
    BiographyV30Rc1ToJSON,
    EmailsV30Rc1,
    EmailsV30Rc1FromJSON,
    EmailsV30Rc1FromJSONTyped,
    EmailsV30Rc1ToJSON,
    KeywordsV30Rc1,
    KeywordsV30Rc1FromJSON,
    KeywordsV30Rc1FromJSONTyped,
    KeywordsV30Rc1ToJSON,
    LastModifiedDateV30Rc1,
    LastModifiedDateV30Rc1FromJSON,
    LastModifiedDateV30Rc1FromJSONTyped,
    LastModifiedDateV30Rc1ToJSON,
    NameV30Rc1,
    NameV30Rc1FromJSON,
    NameV30Rc1FromJSONTyped,
    NameV30Rc1ToJSON,
    OtherNamesV30Rc1,
    OtherNamesV30Rc1FromJSON,
    OtherNamesV30Rc1FromJSONTyped,
    OtherNamesV30Rc1ToJSON,
    PersonExternalIdentifiersV30Rc1,
    PersonExternalIdentifiersV30Rc1FromJSON,
    PersonExternalIdentifiersV30Rc1FromJSONTyped,
    PersonExternalIdentifiersV30Rc1ToJSON,
    ResearcherUrlsV30Rc1,
    ResearcherUrlsV30Rc1FromJSON,
    ResearcherUrlsV30Rc1FromJSONTyped,
    ResearcherUrlsV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PersonV30Rc1
 */
export interface PersonV30Rc1 {
    /**
     * 
     * @type {LastModifiedDateV30Rc1}
     * @memberof PersonV30Rc1
     */
    lastModifiedDate?: LastModifiedDateV30Rc1;
    /**
     * 
     * @type {NameV30Rc1}
     * @memberof PersonV30Rc1
     */
    name?: NameV30Rc1;
    /**
     * 
     * @type {OtherNamesV30Rc1}
     * @memberof PersonV30Rc1
     */
    otherNames?: OtherNamesV30Rc1;
    /**
     * 
     * @type {BiographyV30Rc1}
     * @memberof PersonV30Rc1
     */
    biography?: BiographyV30Rc1;
    /**
     * 
     * @type {ResearcherUrlsV30Rc1}
     * @memberof PersonV30Rc1
     */
    researcherUrls?: ResearcherUrlsV30Rc1;
    /**
     * 
     * @type {EmailsV30Rc1}
     * @memberof PersonV30Rc1
     */
    emails?: EmailsV30Rc1;
    /**
     * 
     * @type {AddressesV30Rc1}
     * @memberof PersonV30Rc1
     */
    addresses?: AddressesV30Rc1;
    /**
     * 
     * @type {KeywordsV30Rc1}
     * @memberof PersonV30Rc1
     */
    keywords?: KeywordsV30Rc1;
    /**
     * 
     * @type {PersonExternalIdentifiersV30Rc1}
     * @memberof PersonV30Rc1
     */
    externalIdentifiers?: PersonExternalIdentifiersV30Rc1;
    /**
     * 
     * @type {string}
     * @memberof PersonV30Rc1
     */
    path?: string;
}

export function PersonV30Rc1FromJSON(json: any): PersonV30Rc1 {
    return PersonV30Rc1FromJSONTyped(json, false);
}

export function PersonV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc1FromJSON(json['last-modified-date']),
        'name': !exists(json, 'name') ? undefined : NameV30Rc1FromJSON(json['name']),
        'otherNames': !exists(json, 'other-names') ? undefined : OtherNamesV30Rc1FromJSON(json['other-names']),
        'biography': !exists(json, 'biography') ? undefined : BiographyV30Rc1FromJSON(json['biography']),
        'researcherUrls': !exists(json, 'researcher-urls') ? undefined : ResearcherUrlsV30Rc1FromJSON(json['researcher-urls']),
        'emails': !exists(json, 'emails') ? undefined : EmailsV30Rc1FromJSON(json['emails']),
        'addresses': !exists(json, 'addresses') ? undefined : AddressesV30Rc1FromJSON(json['addresses']),
        'keywords': !exists(json, 'keywords') ? undefined : KeywordsV30Rc1FromJSON(json['keywords']),
        'externalIdentifiers': !exists(json, 'external-identifiers') ? undefined : PersonExternalIdentifiersV30Rc1FromJSON(json['external-identifiers']),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function PersonV30Rc1ToJSON(value?: PersonV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc1ToJSON(value.lastModifiedDate),
        'name': NameV30Rc1ToJSON(value.name),
        'other-names': OtherNamesV30Rc1ToJSON(value.otherNames),
        'biography': BiographyV30Rc1ToJSON(value.biography),
        'researcher-urls': ResearcherUrlsV30Rc1ToJSON(value.researcherUrls),
        'emails': EmailsV30Rc1ToJSON(value.emails),
        'addresses': AddressesV30Rc1ToJSON(value.addresses),
        'keywords': KeywordsV30Rc1ToJSON(value.keywords),
        'external-identifiers': PersonExternalIdentifiersV30Rc1ToJSON(value.externalIdentifiers),
        'path': value.path,
    };
}


