/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressesV30Rc2,
    AddressesV30Rc2FromJSON,
    AddressesV30Rc2FromJSONTyped,
    AddressesV30Rc2ToJSON,
    BiographyV30Rc2,
    BiographyV30Rc2FromJSON,
    BiographyV30Rc2FromJSONTyped,
    BiographyV30Rc2ToJSON,
    EmailsV30Rc2,
    EmailsV30Rc2FromJSON,
    EmailsV30Rc2FromJSONTyped,
    EmailsV30Rc2ToJSON,
    KeywordsV30Rc2,
    KeywordsV30Rc2FromJSON,
    KeywordsV30Rc2FromJSONTyped,
    KeywordsV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    NameV30Rc2,
    NameV30Rc2FromJSON,
    NameV30Rc2FromJSONTyped,
    NameV30Rc2ToJSON,
    OtherNamesV30Rc2,
    OtherNamesV30Rc2FromJSON,
    OtherNamesV30Rc2FromJSONTyped,
    OtherNamesV30Rc2ToJSON,
    PersonExternalIdentifiersV30Rc2,
    PersonExternalIdentifiersV30Rc2FromJSON,
    PersonExternalIdentifiersV30Rc2FromJSONTyped,
    PersonExternalIdentifiersV30Rc2ToJSON,
    ResearcherUrlsV30Rc2,
    ResearcherUrlsV30Rc2FromJSON,
    ResearcherUrlsV30Rc2FromJSONTyped,
    ResearcherUrlsV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PersonV30Rc2
 */
export interface PersonV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof PersonV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {NameV30Rc2}
     * @memberof PersonV30Rc2
     */
    name?: NameV30Rc2;
    /**
     * 
     * @type {OtherNamesV30Rc2}
     * @memberof PersonV30Rc2
     */
    otherNames?: OtherNamesV30Rc2;
    /**
     * 
     * @type {BiographyV30Rc2}
     * @memberof PersonV30Rc2
     */
    biography?: BiographyV30Rc2;
    /**
     * 
     * @type {ResearcherUrlsV30Rc2}
     * @memberof PersonV30Rc2
     */
    researcherUrls?: ResearcherUrlsV30Rc2;
    /**
     * 
     * @type {EmailsV30Rc2}
     * @memberof PersonV30Rc2
     */
    emails?: EmailsV30Rc2;
    /**
     * 
     * @type {AddressesV30Rc2}
     * @memberof PersonV30Rc2
     */
    addresses?: AddressesV30Rc2;
    /**
     * 
     * @type {KeywordsV30Rc2}
     * @memberof PersonV30Rc2
     */
    keywords?: KeywordsV30Rc2;
    /**
     * 
     * @type {PersonExternalIdentifiersV30Rc2}
     * @memberof PersonV30Rc2
     */
    externalIdentifiers?: PersonExternalIdentifiersV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof PersonV30Rc2
     */
    path?: string;
}

export function PersonV30Rc2FromJSON(json: any): PersonV30Rc2 {
    return PersonV30Rc2FromJSONTyped(json, false);
}

export function PersonV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'name': !exists(json, 'name') ? undefined : NameV30Rc2FromJSON(json['name']),
        'otherNames': !exists(json, 'other-names') ? undefined : OtherNamesV30Rc2FromJSON(json['other-names']),
        'biography': !exists(json, 'biography') ? undefined : BiographyV30Rc2FromJSON(json['biography']),
        'researcherUrls': !exists(json, 'researcher-urls') ? undefined : ResearcherUrlsV30Rc2FromJSON(json['researcher-urls']),
        'emails': !exists(json, 'emails') ? undefined : EmailsV30Rc2FromJSON(json['emails']),
        'addresses': !exists(json, 'addresses') ? undefined : AddressesV30Rc2FromJSON(json['addresses']),
        'keywords': !exists(json, 'keywords') ? undefined : KeywordsV30Rc2FromJSON(json['keywords']),
        'externalIdentifiers': !exists(json, 'external-identifiers') ? undefined : PersonExternalIdentifiersV30Rc2FromJSON(json['external-identifiers']),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function PersonV30Rc2ToJSON(value?: PersonV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'name': NameV30Rc2ToJSON(value.name),
        'other-names': OtherNamesV30Rc2ToJSON(value.otherNames),
        'biography': BiographyV30Rc2ToJSON(value.biography),
        'researcher-urls': ResearcherUrlsV30Rc2ToJSON(value.researcherUrls),
        'emails': EmailsV30Rc2ToJSON(value.emails),
        'addresses': AddressesV30Rc2ToJSON(value.addresses),
        'keywords': KeywordsV30Rc2ToJSON(value.keywords),
        'external-identifiers': PersonExternalIdentifiersV30Rc2ToJSON(value.externalIdentifiers),
        'path': value.path,
    };
}


