/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    PersonExternalIdentifierV30Rc2,
    PersonExternalIdentifierV30Rc2FromJSON,
    PersonExternalIdentifierV30Rc2FromJSONTyped,
    PersonExternalIdentifierV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PersonExternalIdentifiersV30Rc2
 */
export interface PersonExternalIdentifiersV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof PersonExternalIdentifiersV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {Array<PersonExternalIdentifierV30Rc2>}
     * @memberof PersonExternalIdentifiersV30Rc2
     */
    externalIdentifier?: Array<PersonExternalIdentifierV30Rc2>;
    /**
     * 
     * @type {string}
     * @memberof PersonExternalIdentifiersV30Rc2
     */
    path?: string;
}

export function PersonExternalIdentifiersV30Rc2FromJSON(json: any): PersonExternalIdentifiersV30Rc2 {
    return PersonExternalIdentifiersV30Rc2FromJSONTyped(json, false);
}

export function PersonExternalIdentifiersV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonExternalIdentifiersV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'externalIdentifier': !exists(json, 'external-identifier') ? undefined : ((json['external-identifier'] as Array<any>).map(PersonExternalIdentifierV30Rc2FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function PersonExternalIdentifiersV30Rc2ToJSON(value?: PersonExternalIdentifiersV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'external-identifier': value.externalIdentifier === undefined ? undefined : ((value.externalIdentifier as Array<any>).map(PersonExternalIdentifierV30Rc2ToJSON)),
        'path': value.path,
    };
}


