/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferencesV20
 */
export interface PreferencesV20 {
    /**
     * 
     * @type {string}
     * @memberof PreferencesV20
     */
    locale?: PreferencesV20LocaleEnum;
}

/**
* @export
* @enum {string}
*/
export enum PreferencesV20LocaleEnum {
    Ar = 'AR',
    En = 'EN',
    Es = 'ES',
    Fr = 'FR',
    Ko = 'KO',
    Pt = 'PT',
    Ru = 'RU',
    ZhCn = 'ZH_CN',
    ZhTw = 'ZH_TW',
    It = 'IT',
    Ja = 'JA',
    Xx = 'XX'
}

export function PreferencesV20FromJSON(json: any): PreferencesV20 {
    return PreferencesV20FromJSONTyped(json, false);
}

export function PreferencesV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferencesV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
    };
}

export function PreferencesV20ToJSON(value?: PreferencesV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locale': value.locale,
    };
}


