/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DayV30Rc2,
    DayV30Rc2FromJSON,
    DayV30Rc2FromJSONTyped,
    DayV30Rc2ToJSON,
    MonthV30Rc2,
    MonthV30Rc2FromJSON,
    MonthV30Rc2FromJSONTyped,
    MonthV30Rc2ToJSON,
    YearV30Rc2,
    YearV30Rc2FromJSON,
    YearV30Rc2FromJSONTyped,
    YearV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface PublicationDateV30Rc2
 */
export interface PublicationDateV30Rc2 {
    /**
     * 
     * @type {YearV30Rc2}
     * @memberof PublicationDateV30Rc2
     */
    year: YearV30Rc2;
    /**
     * 
     * @type {MonthV30Rc2}
     * @memberof PublicationDateV30Rc2
     */
    month?: MonthV30Rc2;
    /**
     * 
     * @type {DayV30Rc2}
     * @memberof PublicationDateV30Rc2
     */
    day?: DayV30Rc2;
}

export function PublicationDateV30Rc2FromJSON(json: any): PublicationDateV30Rc2 {
    return PublicationDateV30Rc2FromJSONTyped(json, false);
}

export function PublicationDateV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicationDateV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': YearV30Rc2FromJSON(json['year']),
        'month': !exists(json, 'month') ? undefined : MonthV30Rc2FromJSON(json['month']),
        'day': !exists(json, 'day') ? undefined : DayV30Rc2FromJSON(json['day']),
    };
}

export function PublicationDateV30Rc2ToJSON(value?: PublicationDateV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': YearV30Rc2ToJSON(value.year),
        'month': MonthV30Rc2ToJSON(value.month),
        'day': DayV30Rc2ToJSON(value.day),
    };
}


