/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AffiliationGroupV30QualificationSummaryV30,
    AffiliationGroupV30QualificationSummaryV30FromJSON,
    AffiliationGroupV30QualificationSummaryV30FromJSONTyped,
    AffiliationGroupV30QualificationSummaryV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface QualificationsV30
 */
export interface QualificationsV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof QualificationsV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {Array<AffiliationGroupV30QualificationSummaryV30>}
     * @memberof QualificationsV30
     */
    affiliationGroup?: Array<AffiliationGroupV30QualificationSummaryV30>;
    /**
     * 
     * @type {string}
     * @memberof QualificationsV30
     */
    path?: string;
}

export function QualificationsV30FromJSON(json: any): QualificationsV30 {
    return QualificationsV30FromJSONTyped(json, false);
}

export function QualificationsV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): QualificationsV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'affiliationGroup': !exists(json, 'affiliation-group') ? undefined : ((json['affiliation-group'] as Array<any>).map(AffiliationGroupV30QualificationSummaryV30FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function QualificationsV30ToJSON(value?: QualificationsV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'affiliation-group': value.affiliationGroup === undefined ? undefined : ((value.affiliationGroup as Array<any>).map(AffiliationGroupV30QualificationSummaryV30ToJSON)),
        'path': value.path,
    };
}


