/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivitiesSummaryV30,
    ActivitiesSummaryV30FromJSON,
    ActivitiesSummaryV30FromJSONTyped,
    ActivitiesSummaryV30ToJSON,
    HistoryV30,
    HistoryV30FromJSON,
    HistoryV30FromJSONTyped,
    HistoryV30ToJSON,
    OrcidIdentifierV30,
    OrcidIdentifierV30FromJSON,
    OrcidIdentifierV30FromJSONTyped,
    OrcidIdentifierV30ToJSON,
    PersonV30,
    PersonV30FromJSON,
    PersonV30FromJSONTyped,
    PersonV30ToJSON,
    PreferencesV30,
    PreferencesV30FromJSON,
    PreferencesV30FromJSONTyped,
    PreferencesV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface RecordV30
 */
export interface RecordV30 {
    /**
     * 
     * @type {OrcidIdentifierV30}
     * @memberof RecordV30
     */
    orcidIdentifier?: OrcidIdentifierV30;
    /**
     * 
     * @type {PreferencesV30}
     * @memberof RecordV30
     */
    preferences?: PreferencesV30;
    /**
     * 
     * @type {HistoryV30}
     * @memberof RecordV30
     */
    history?: HistoryV30;
    /**
     * 
     * @type {PersonV30}
     * @memberof RecordV30
     */
    person?: PersonV30;
    /**
     * 
     * @type {ActivitiesSummaryV30}
     * @memberof RecordV30
     */
    activitiesSummary?: ActivitiesSummaryV30;
    /**
     * 
     * @type {string}
     * @memberof RecordV30
     */
    path?: string;
}

export function RecordV30FromJSON(json: any): RecordV30 {
    return RecordV30FromJSONTyped(json, false);
}

export function RecordV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orcidIdentifier': !exists(json, 'orcid-identifier') ? undefined : OrcidIdentifierV30FromJSON(json['orcid-identifier']),
        'preferences': !exists(json, 'preferences') ? undefined : PreferencesV30FromJSON(json['preferences']),
        'history': !exists(json, 'history') ? undefined : HistoryV30FromJSON(json['history']),
        'person': !exists(json, 'person') ? undefined : PersonV30FromJSON(json['person']),
        'activitiesSummary': !exists(json, 'activities-summary') ? undefined : ActivitiesSummaryV30FromJSON(json['activities-summary']),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function RecordV30ToJSON(value?: RecordV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orcid-identifier': OrcidIdentifierV30ToJSON(value.orcidIdentifier),
        'preferences': PreferencesV30ToJSON(value.preferences),
        'history': HistoryV30ToJSON(value.history),
        'person': PersonV30ToJSON(value.person),
        'activities-summary': ActivitiesSummaryV30ToJSON(value.activitiesSummary),
        'path': value.path,
    };
}


