/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivitiesSummaryV30Rc2,
    ActivitiesSummaryV30Rc2FromJSON,
    ActivitiesSummaryV30Rc2FromJSONTyped,
    ActivitiesSummaryV30Rc2ToJSON,
    HistoryV30Rc2,
    HistoryV30Rc2FromJSON,
    HistoryV30Rc2FromJSONTyped,
    HistoryV30Rc2ToJSON,
    OrcidIdentifierV30Rc2,
    OrcidIdentifierV30Rc2FromJSON,
    OrcidIdentifierV30Rc2FromJSONTyped,
    OrcidIdentifierV30Rc2ToJSON,
    PersonV30Rc2,
    PersonV30Rc2FromJSON,
    PersonV30Rc2FromJSONTyped,
    PersonV30Rc2ToJSON,
    PreferencesV30Rc2,
    PreferencesV30Rc2FromJSON,
    PreferencesV30Rc2FromJSONTyped,
    PreferencesV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface RecordV30Rc2
 */
export interface RecordV30Rc2 {
    /**
     * 
     * @type {OrcidIdentifierV30Rc2}
     * @memberof RecordV30Rc2
     */
    orcidIdentifier?: OrcidIdentifierV30Rc2;
    /**
     * 
     * @type {PreferencesV30Rc2}
     * @memberof RecordV30Rc2
     */
    preferences?: PreferencesV30Rc2;
    /**
     * 
     * @type {HistoryV30Rc2}
     * @memberof RecordV30Rc2
     */
    history?: HistoryV30Rc2;
    /**
     * 
     * @type {PersonV30Rc2}
     * @memberof RecordV30Rc2
     */
    person?: PersonV30Rc2;
    /**
     * 
     * @type {ActivitiesSummaryV30Rc2}
     * @memberof RecordV30Rc2
     */
    activitiesSummary?: ActivitiesSummaryV30Rc2;
    /**
     * 
     * @type {string}
     * @memberof RecordV30Rc2
     */
    path?: string;
}

export function RecordV30Rc2FromJSON(json: any): RecordV30Rc2 {
    return RecordV30Rc2FromJSONTyped(json, false);
}

export function RecordV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orcidIdentifier': !exists(json, 'orcid-identifier') ? undefined : OrcidIdentifierV30Rc2FromJSON(json['orcid-identifier']),
        'preferences': !exists(json, 'preferences') ? undefined : PreferencesV30Rc2FromJSON(json['preferences']),
        'history': !exists(json, 'history') ? undefined : HistoryV30Rc2FromJSON(json['history']),
        'person': !exists(json, 'person') ? undefined : PersonV30Rc2FromJSON(json['person']),
        'activitiesSummary': !exists(json, 'activities-summary') ? undefined : ActivitiesSummaryV30Rc2FromJSON(json['activities-summary']),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function RecordV30Rc2ToJSON(value?: RecordV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orcid-identifier': OrcidIdentifierV30Rc2ToJSON(value.orcidIdentifier),
        'preferences': PreferencesV30Rc2ToJSON(value.preferences),
        'history': HistoryV30Rc2ToJSON(value.history),
        'person': PersonV30Rc2ToJSON(value.person),
        'activities-summary': ActivitiesSummaryV30Rc2ToJSON(value.activitiesSummary),
        'path': value.path,
    };
}


