/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrganizationV30Rc1,
    OrganizationV30Rc1FromJSON,
    OrganizationV30Rc1FromJSONTyped,
    OrganizationV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourceHostsV30Rc1
 */
export interface ResearchResourceHostsV30Rc1 {
    /**
     * 
     * @type {Array<OrganizationV30Rc1>}
     * @memberof ResearchResourceHostsV30Rc1
     */
    organization?: Array<OrganizationV30Rc1>;
}

export function ResearchResourceHostsV30Rc1FromJSON(json: any): ResearchResourceHostsV30Rc1 {
    return ResearchResourceHostsV30Rc1FromJSONTyped(json, false);
}

export function ResearchResourceHostsV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourceHostsV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': !exists(json, 'organization') ? undefined : ((json['organization'] as Array<any>).map(OrganizationV30Rc1FromJSON)),
    };
}

export function ResearchResourceHostsV30Rc1ToJSON(value?: ResearchResourceHostsV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': value.organization === undefined ? undefined : ((value.organization as Array<any>).map(OrganizationV30Rc1ToJSON)),
    };
}


