/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30Rc2,
    ExternalIDsV30Rc2FromJSON,
    ExternalIDsV30Rc2FromJSONTyped,
    ExternalIDsV30Rc2ToJSON,
    FuzzyDateV30Rc2,
    FuzzyDateV30Rc2FromJSON,
    FuzzyDateV30Rc2FromJSONTyped,
    FuzzyDateV30Rc2ToJSON,
    ResearchResourceHostsV30Rc2,
    ResearchResourceHostsV30Rc2FromJSON,
    ResearchResourceHostsV30Rc2FromJSONTyped,
    ResearchResourceHostsV30Rc2ToJSON,
    ResearchResourceTitleV30Rc2,
    ResearchResourceTitleV30Rc2FromJSON,
    ResearchResourceTitleV30Rc2FromJSONTyped,
    ResearchResourceTitleV30Rc2ToJSON,
    UrlV30Rc2,
    UrlV30Rc2FromJSON,
    UrlV30Rc2FromJSONTyped,
    UrlV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourceProposalV30Rc2
 */
export interface ResearchResourceProposalV30Rc2 {
    /**
     * 
     * @type {ResearchResourceTitleV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    title?: ResearchResourceTitleV30Rc2;
    /**
     * 
     * @type {ResearchResourceHostsV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    hosts?: ResearchResourceHostsV30Rc2;
    /**
     * 
     * @type {ExternalIDsV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    externalIds?: ExternalIDsV30Rc2;
    /**
     * 
     * @type {FuzzyDateV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    startDate?: FuzzyDateV30Rc2;
    /**
     * 
     * @type {FuzzyDateV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    endDate?: FuzzyDateV30Rc2;
    /**
     * 
     * @type {UrlV30Rc2}
     * @memberof ResearchResourceProposalV30Rc2
     */
    url?: UrlV30Rc2;
}

export function ResearchResourceProposalV30Rc2FromJSON(json: any): ResearchResourceProposalV30Rc2 {
    return ResearchResourceProposalV30Rc2FromJSONTyped(json, false);
}

export function ResearchResourceProposalV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourceProposalV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : ResearchResourceTitleV30Rc2FromJSON(json['title']),
        'hosts': !exists(json, 'hosts') ? undefined : ResearchResourceHostsV30Rc2FromJSON(json['hosts']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30Rc2FromJSON(json['external-ids']),
        'startDate': !exists(json, 'start-date') ? undefined : FuzzyDateV30Rc2FromJSON(json['start-date']),
        'endDate': !exists(json, 'end-date') ? undefined : FuzzyDateV30Rc2FromJSON(json['end-date']),
        'url': !exists(json, 'url') ? undefined : UrlV30Rc2FromJSON(json['url']),
    };
}

export function ResearchResourceProposalV30Rc2ToJSON(value?: ResearchResourceProposalV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': ResearchResourceTitleV30Rc2ToJSON(value.title),
        'hosts': ResearchResourceHostsV30Rc2ToJSON(value.hosts),
        'external-ids': ExternalIDsV30Rc2ToJSON(value.externalIds),
        'start-date': FuzzyDateV30Rc2ToJSON(value.startDate),
        'end-date': FuzzyDateV30Rc2ToJSON(value.endDate),
        'url': UrlV30Rc2ToJSON(value.url),
    };
}


