/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    ResearcherUrlV30Rc2,
    ResearcherUrlV30Rc2FromJSON,
    ResearcherUrlV30Rc2FromJSONTyped,
    ResearcherUrlV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearcherUrlsV30Rc2
 */
export interface ResearcherUrlsV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof ResearcherUrlsV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {Array<ResearcherUrlV30Rc2>}
     * @memberof ResearcherUrlsV30Rc2
     */
    researcherUrl?: Array<ResearcherUrlV30Rc2>;
    /**
     * 
     * @type {string}
     * @memberof ResearcherUrlsV30Rc2
     */
    path?: string;
}

export function ResearcherUrlsV30Rc2FromJSON(json: any): ResearcherUrlsV30Rc2 {
    return ResearcherUrlsV30Rc2FromJSONTyped(json, false);
}

export function ResearcherUrlsV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearcherUrlsV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'researcherUrl': !exists(json, 'researcher-url') ? undefined : ((json['researcher-url'] as Array<any>).map(ResearcherUrlV30Rc2FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ResearcherUrlsV30Rc2ToJSON(value?: ResearcherUrlsV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'researcher-url': value.researcherUrl === undefined ? undefined : ((value.researcherUrl as Array<any>).map(ResearcherUrlV30Rc2ToJSON)),
        'path': value.path,
    };
}


