/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    ResearchResourceGroupV30Rc2,
    ResearchResourceGroupV30Rc2FromJSON,
    ResearchResourceGroupV30Rc2FromJSONTyped,
    ResearchResourceGroupV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourcesV30Rc2
 */
export interface ResearchResourcesV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof ResearchResourcesV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {Array<ResearchResourceGroupV30Rc2>}
     * @memberof ResearchResourcesV30Rc2
     */
    group?: Array<ResearchResourceGroupV30Rc2>;
    /**
     * 
     * @type {string}
     * @memberof ResearchResourcesV30Rc2
     */
    path?: string;
}

export function ResearchResourcesV30Rc2FromJSON(json: any): ResearchResourcesV30Rc2 {
    return ResearchResourcesV30Rc2FromJSONTyped(json, false);
}

export function ResearchResourcesV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourcesV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'group': !exists(json, 'group') ? undefined : ((json['group'] as Array<any>).map(ResearchResourceGroupV30Rc2FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ResearchResourcesV30Rc2ToJSON(value?: ResearchResourcesV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'group': value.group === undefined ? undefined : ((value.group as Array<any>).map(ResearchResourceGroupV30Rc2ToJSON)),
        'path': value.path,
    };
}


