/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatedDateV30Rc1,
    CreatedDateV30Rc1FromJSON,
    CreatedDateV30Rc1FromJSONTyped,
    CreatedDateV30Rc1ToJSON,
    LastModifiedDateV30Rc1,
    LastModifiedDateV30Rc1FromJSON,
    LastModifiedDateV30Rc1FromJSONTyped,
    LastModifiedDateV30Rc1ToJSON,
    SourceV30Rc1,
    SourceV30Rc1FromJSON,
    SourceV30Rc1FromJSONTyped,
    SourceV30Rc1ToJSON,
    UrlV30Rc1,
    UrlV30Rc1FromJSON,
    UrlV30Rc1FromJSONTyped,
    UrlV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearcherUrlV30Rc1
 */
export interface ResearcherUrlV30Rc1 {
    /**
     * 
     * @type {CreatedDateV30Rc1}
     * @memberof ResearcherUrlV30Rc1
     */
    createdDate?: CreatedDateV30Rc1;
    /**
     * 
     * @type {LastModifiedDateV30Rc1}
     * @memberof ResearcherUrlV30Rc1
     */
    lastModifiedDate?: LastModifiedDateV30Rc1;
    /**
     * 
     * @type {SourceV30Rc1}
     * @memberof ResearcherUrlV30Rc1
     */
    source?: SourceV30Rc1;
    /**
     * 
     * @type {string}
     * @memberof ResearcherUrlV30Rc1
     */
    urlName?: string;
    /**
     * 
     * @type {UrlV30Rc1}
     * @memberof ResearcherUrlV30Rc1
     */
    url?: UrlV30Rc1;
    /**
     * 
     * @type {string}
     * @memberof ResearcherUrlV30Rc1
     */
    visibility?: ResearcherUrlV30Rc1VisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof ResearcherUrlV30Rc1
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof ResearcherUrlV30Rc1
     */
    putCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ResearcherUrlV30Rc1
     */
    displayIndex?: number;
}

/**
* @export
* @enum {string}
*/
export enum ResearcherUrlV30Rc1VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function ResearcherUrlV30Rc1FromJSON(json: any): ResearcherUrlV30Rc1 {
    return ResearcherUrlV30Rc1FromJSONTyped(json, false);
}

export function ResearcherUrlV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearcherUrlV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV30Rc1FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc1FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV30Rc1FromJSON(json['source']),
        'urlName': !exists(json, 'url-name') ? undefined : json['url-name'],
        'url': !exists(json, 'url') ? undefined : UrlV30Rc1FromJSON(json['url']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'displayIndex': !exists(json, 'display-index') ? undefined : json['display-index'],
    };
}

export function ResearcherUrlV30Rc1ToJSON(value?: ResearcherUrlV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV30Rc1ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV30Rc1ToJSON(value.lastModifiedDate),
        'source': SourceV30Rc1ToJSON(value.source),
        'url-name': value.urlName,
        'url': UrlV30Rc1ToJSON(value.url),
        'visibility': value.visibility,
        'path': value.path,
        'put-code': value.putCode,
        'display-index': value.displayIndex,
    };
}


