/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30,
    ExternalIDsV30FromJSON,
    ExternalIDsV30FromJSONTyped,
    ExternalIDsV30ToJSON,
    FuzzyDateV30,
    FuzzyDateV30FromJSON,
    FuzzyDateV30FromJSONTyped,
    FuzzyDateV30ToJSON,
    ResearchResourceHostsV30,
    ResearchResourceHostsV30FromJSON,
    ResearchResourceHostsV30FromJSONTyped,
    ResearchResourceHostsV30ToJSON,
    ResearchResourceTitleV30,
    ResearchResourceTitleV30FromJSON,
    ResearchResourceTitleV30FromJSONTyped,
    ResearchResourceTitleV30ToJSON,
    UrlV30,
    UrlV30FromJSON,
    UrlV30FromJSONTyped,
    UrlV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourceProposalV30
 */
export interface ResearchResourceProposalV30 {
    /**
     * 
     * @type {ResearchResourceTitleV30}
     * @memberof ResearchResourceProposalV30
     */
    title?: ResearchResourceTitleV30;
    /**
     * 
     * @type {ResearchResourceHostsV30}
     * @memberof ResearchResourceProposalV30
     */
    hosts?: ResearchResourceHostsV30;
    /**
     * 
     * @type {ExternalIDsV30}
     * @memberof ResearchResourceProposalV30
     */
    externalIds?: ExternalIDsV30;
    /**
     * 
     * @type {FuzzyDateV30}
     * @memberof ResearchResourceProposalV30
     */
    startDate?: FuzzyDateV30;
    /**
     * 
     * @type {FuzzyDateV30}
     * @memberof ResearchResourceProposalV30
     */
    endDate?: FuzzyDateV30;
    /**
     * 
     * @type {UrlV30}
     * @memberof ResearchResourceProposalV30
     */
    url?: UrlV30;
}

export function ResearchResourceProposalV30FromJSON(json: any): ResearchResourceProposalV30 {
    return ResearchResourceProposalV30FromJSONTyped(json, false);
}

export function ResearchResourceProposalV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourceProposalV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : ResearchResourceTitleV30FromJSON(json['title']),
        'hosts': !exists(json, 'hosts') ? undefined : ResearchResourceHostsV30FromJSON(json['hosts']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30FromJSON(json['external-ids']),
        'startDate': !exists(json, 'start-date') ? undefined : FuzzyDateV30FromJSON(json['start-date']),
        'endDate': !exists(json, 'end-date') ? undefined : FuzzyDateV30FromJSON(json['end-date']),
        'url': !exists(json, 'url') ? undefined : UrlV30FromJSON(json['url']),
    };
}

export function ResearchResourceProposalV30ToJSON(value?: ResearchResourceProposalV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': ResearchResourceTitleV30ToJSON(value.title),
        'hosts': ResearchResourceHostsV30ToJSON(value.hosts),
        'external-ids': ExternalIDsV30ToJSON(value.externalIds),
        'start-date': FuzzyDateV30ToJSON(value.startDate),
        'end-date': FuzzyDateV30ToJSON(value.endDate),
        'url': UrlV30ToJSON(value.url),
    };
}


