/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30,
    ExternalIDsV30FromJSON,
    ExternalIDsV30FromJSONTyped,
    ExternalIDsV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
    ResearchResourceSummaryV30,
    ResearchResourceSummaryV30FromJSON,
    ResearchResourceSummaryV30FromJSONTyped,
    ResearchResourceSummaryV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourceGroupV30
 */
export interface ResearchResourceGroupV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof ResearchResourceGroupV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {ExternalIDsV30}
     * @memberof ResearchResourceGroupV30
     */
    externalIds?: ExternalIDsV30;
    /**
     * 
     * @type {Array<ResearchResourceSummaryV30>}
     * @memberof ResearchResourceGroupV30
     */
    researchResourceSummary?: Array<ResearchResourceSummaryV30>;
}

export function ResearchResourceGroupV30FromJSON(json: any): ResearchResourceGroupV30 {
    return ResearchResourceGroupV30FromJSONTyped(json, false);
}

export function ResearchResourceGroupV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourceGroupV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30FromJSON(json['external-ids']),
        'researchResourceSummary': !exists(json, 'research-resource-summary') ? undefined : ((json['research-resource-summary'] as Array<any>).map(ResearchResourceSummaryV30FromJSON)),
    };
}

export function ResearchResourceGroupV30ToJSON(value?: ResearchResourceGroupV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'external-ids': ExternalIDsV30ToJSON(value.externalIds),
        'research-resource-summary': value.researchResourceSummary === undefined ? undefined : ((value.researchResourceSummary as Array<any>).map(ResearchResourceSummaryV30ToJSON)),
    };
}


