/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30Rc2,
    ExternalIDsV30Rc2FromJSON,
    ExternalIDsV30Rc2FromJSONTyped,
    ExternalIDsV30Rc2ToJSON,
    LastModifiedDateV30Rc2,
    LastModifiedDateV30Rc2FromJSON,
    LastModifiedDateV30Rc2FromJSONTyped,
    LastModifiedDateV30Rc2ToJSON,
    ResearchResourceSummaryV30Rc2,
    ResearchResourceSummaryV30Rc2FromJSON,
    ResearchResourceSummaryV30Rc2FromJSONTyped,
    ResearchResourceSummaryV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearchResourceGroupV30Rc2
 */
export interface ResearchResourceGroupV30Rc2 {
    /**
     * 
     * @type {LastModifiedDateV30Rc2}
     * @memberof ResearchResourceGroupV30Rc2
     */
    lastModifiedDate?: LastModifiedDateV30Rc2;
    /**
     * 
     * @type {ExternalIDsV30Rc2}
     * @memberof ResearchResourceGroupV30Rc2
     */
    externalIds?: ExternalIDsV30Rc2;
    /**
     * 
     * @type {Array<ResearchResourceSummaryV30Rc2>}
     * @memberof ResearchResourceGroupV30Rc2
     */
    researchResourceSummary?: Array<ResearchResourceSummaryV30Rc2>;
}

export function ResearchResourceGroupV30Rc2FromJSON(json: any): ResearchResourceGroupV30Rc2 {
    return ResearchResourceGroupV30Rc2FromJSONTyped(json, false);
}

export function ResearchResourceGroupV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearchResourceGroupV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc2FromJSON(json['last-modified-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30Rc2FromJSON(json['external-ids']),
        'researchResourceSummary': !exists(json, 'research-resource-summary') ? undefined : ((json['research-resource-summary'] as Array<any>).map(ResearchResourceSummaryV30Rc2FromJSON)),
    };
}

export function ResearchResourceGroupV30Rc2ToJSON(value?: ResearchResourceGroupV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc2ToJSON(value.lastModifiedDate),
        'external-ids': ExternalIDsV30Rc2ToJSON(value.externalIds),
        'research-resource-summary': value.researchResourceSummary === undefined ? undefined : ((value.researchResourceSummary as Array<any>).map(ResearchResourceSummaryV30Rc2ToJSON)),
    };
}


