/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LastModifiedDateV30Rc1,
    LastModifiedDateV30Rc1FromJSON,
    LastModifiedDateV30Rc1FromJSONTyped,
    LastModifiedDateV30Rc1ToJSON,
    ResearcherUrlV30Rc1,
    ResearcherUrlV30Rc1FromJSON,
    ResearcherUrlV30Rc1FromJSONTyped,
    ResearcherUrlV30Rc1ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResearcherUrlsV30Rc1
 */
export interface ResearcherUrlsV30Rc1 {
    /**
     * 
     * @type {LastModifiedDateV30Rc1}
     * @memberof ResearcherUrlsV30Rc1
     */
    lastModifiedDate?: LastModifiedDateV30Rc1;
    /**
     * 
     * @type {Array<ResearcherUrlV30Rc1>}
     * @memberof ResearcherUrlsV30Rc1
     */
    researcherUrl?: Array<ResearcherUrlV30Rc1>;
    /**
     * 
     * @type {string}
     * @memberof ResearcherUrlsV30Rc1
     */
    path?: string;
}

export function ResearcherUrlsV30Rc1FromJSON(json: any): ResearcherUrlsV30Rc1 {
    return ResearcherUrlsV30Rc1FromJSONTyped(json, false);
}

export function ResearcherUrlsV30Rc1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResearcherUrlsV30Rc1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30Rc1FromJSON(json['last-modified-date']),
        'researcherUrl': !exists(json, 'researcher-url') ? undefined : ((json['researcher-url'] as Array<any>).map(ResearcherUrlV30Rc1FromJSON)),
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function ResearcherUrlsV30Rc1ToJSON(value?: ResearcherUrlsV30Rc1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30Rc1ToJSON(value.lastModifiedDate),
        'researcher-url': value.researcherUrl === undefined ? undefined : ((value.researcherUrl as Array<any>).map(ResearcherUrlV30Rc1ToJSON)),
        'path': value.path,
    };
}


