/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SourceClientIdV30,
    SourceClientIdV30FromJSON,
    SourceClientIdV30FromJSONTyped,
    SourceClientIdV30ToJSON,
    SourceNameV30,
    SourceNameV30FromJSON,
    SourceNameV30FromJSONTyped,
    SourceNameV30ToJSON,
    SourceOrcidV30,
    SourceOrcidV30FromJSON,
    SourceOrcidV30FromJSONTyped,
    SourceOrcidV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface SourceV30
 */
export interface SourceV30 {
    /**
     * 
     * @type {SourceOrcidV30}
     * @memberof SourceV30
     */
    sourceOrcid?: SourceOrcidV30;
    /**
     * 
     * @type {SourceClientIdV30}
     * @memberof SourceV30
     */
    sourceClientId?: SourceClientIdV30;
    /**
     * 
     * @type {SourceNameV30}
     * @memberof SourceV30
     */
    sourceName?: SourceNameV30;
    /**
     * 
     * @type {SourceOrcidV30}
     * @memberof SourceV30
     */
    assertionOriginOrcid?: SourceOrcidV30;
    /**
     * 
     * @type {SourceClientIdV30}
     * @memberof SourceV30
     */
    assertionOriginClientId?: SourceClientIdV30;
    /**
     * 
     * @type {SourceNameV30}
     * @memberof SourceV30
     */
    assertionOriginName?: SourceNameV30;
}

export function SourceV30FromJSON(json: any): SourceV30 {
    return SourceV30FromJSONTyped(json, false);
}

export function SourceV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceOrcid': !exists(json, 'source-orcid') ? undefined : SourceOrcidV30FromJSON(json['source-orcid']),
        'sourceClientId': !exists(json, 'source-client-id') ? undefined : SourceClientIdV30FromJSON(json['source-client-id']),
        'sourceName': !exists(json, 'source-name') ? undefined : SourceNameV30FromJSON(json['source-name']),
        'assertionOriginOrcid': !exists(json, 'assertion-origin-orcid') ? undefined : SourceOrcidV30FromJSON(json['assertion-origin-orcid']),
        'assertionOriginClientId': !exists(json, 'assertion-origin-client-id') ? undefined : SourceClientIdV30FromJSON(json['assertion-origin-client-id']),
        'assertionOriginName': !exists(json, 'assertion-origin-name') ? undefined : SourceNameV30FromJSON(json['assertion-origin-name']),
    };
}

export function SourceV30ToJSON(value?: SourceV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source-orcid': SourceOrcidV30ToJSON(value.sourceOrcid),
        'source-client-id': SourceClientIdV30ToJSON(value.sourceClientId),
        'source-name': SourceNameV30ToJSON(value.sourceName),
        'assertion-origin-orcid': SourceOrcidV30ToJSON(value.assertionOriginOrcid),
        'assertion-origin-client-id': SourceClientIdV30ToJSON(value.assertionOriginClientId),
        'assertion-origin-name': SourceNameV30ToJSON(value.assertionOriginName),
    };
}


