/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionDateV30
 */
export interface SubmissionDateV30 {
    /**
     * 
     * @type {Date}
     * @memberof SubmissionDateV30
     */
    readonly value?: Date;
}

export function SubmissionDateV30FromJSON(json: any): SubmissionDateV30 {
    return SubmissionDateV30FromJSONTyped(json, false);
}

export function SubmissionDateV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionDateV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : (new Date(json['value'])),
    };
}

export function SubmissionDateV30ToJSON(value?: SubmissionDateV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


