/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalIDsV30,
    ExternalIDsV30FromJSON,
    ExternalIDsV30FromJSONTyped,
    ExternalIDsV30ToJSON,
    LastModifiedDateV30,
    LastModifiedDateV30FromJSON,
    LastModifiedDateV30FromJSONTyped,
    LastModifiedDateV30ToJSON,
    WorkSummaryV30,
    WorkSummaryV30FromJSON,
    WorkSummaryV30FromJSONTyped,
    WorkSummaryV30ToJSON,
} from './';

/**
 * 
 * @export
 * @interface WorkGroupV30
 */
export interface WorkGroupV30 {
    /**
     * 
     * @type {LastModifiedDateV30}
     * @memberof WorkGroupV30
     */
    lastModifiedDate?: LastModifiedDateV30;
    /**
     * 
     * @type {ExternalIDsV30}
     * @memberof WorkGroupV30
     */
    externalIds?: ExternalIDsV30;
    /**
     * 
     * @type {Array<WorkSummaryV30>}
     * @memberof WorkGroupV30
     */
    workSummary?: Array<WorkSummaryV30>;
}

export function WorkGroupV30FromJSON(json: any): WorkGroupV30 {
    return WorkGroupV30FromJSONTyped(json, false);
}

export function WorkGroupV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkGroupV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV30FromJSON(json['last-modified-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV30FromJSON(json['external-ids']),
        'workSummary': !exists(json, 'work-summary') ? undefined : ((json['work-summary'] as Array<any>).map(WorkSummaryV30FromJSON)),
    };
}

export function WorkGroupV30ToJSON(value?: WorkGroupV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last-modified-date': LastModifiedDateV30ToJSON(value.lastModifiedDate),
        'external-ids': ExternalIDsV30ToJSON(value.externalIds),
        'work-summary': value.workSummary === undefined ? undefined : ((value.workSummary as Array<any>).map(WorkSummaryV30ToJSON)),
    };
}


