/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContributorV30Rc2,
    ContributorV30Rc2FromJSON,
    ContributorV30Rc2FromJSONTyped,
    ContributorV30Rc2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface WorkContributorsV30Rc2
 */
export interface WorkContributorsV30Rc2 {
    /**
     * 
     * @type {Array<ContributorV30Rc2>}
     * @memberof WorkContributorsV30Rc2
     */
    contributor?: Array<ContributorV30Rc2>;
}

export function WorkContributorsV30Rc2FromJSON(json: any): WorkContributorsV30Rc2 {
    return WorkContributorsV30Rc2FromJSONTyped(json, false);
}

export function WorkContributorsV30Rc2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkContributorsV30Rc2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contributor': !exists(json, 'contributor') ? undefined : ((json['contributor'] as Array<any>).map(ContributorV30Rc2FromJSON)),
    };
}

export function WorkContributorsV30Rc2ToJSON(value?: WorkContributorsV30Rc2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contributor': value.contributor === undefined ? undefined : ((value.contributor as Array<any>).map(ContributorV30Rc2ToJSON)),
    };
}


