/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Citation,
    CitationFromJSON,
    CitationFromJSONTyped,
    CitationToJSON,
    CountryV20,
    CountryV20FromJSON,
    CountryV20FromJSONTyped,
    CountryV20ToJSON,
    CreatedDateV20,
    CreatedDateV20FromJSON,
    CreatedDateV20FromJSONTyped,
    CreatedDateV20ToJSON,
    ExternalIDsV20,
    ExternalIDsV20FromJSON,
    ExternalIDsV20FromJSONTyped,
    ExternalIDsV20ToJSON,
    LastModifiedDateV20,
    LastModifiedDateV20FromJSON,
    LastModifiedDateV20FromJSONTyped,
    LastModifiedDateV20ToJSON,
    PublicationDateV20,
    PublicationDateV20FromJSON,
    PublicationDateV20FromJSONTyped,
    PublicationDateV20ToJSON,
    SourceV20,
    SourceV20FromJSON,
    SourceV20FromJSONTyped,
    SourceV20ToJSON,
    TitleV20,
    TitleV20FromJSON,
    TitleV20FromJSONTyped,
    TitleV20ToJSON,
    UrlV20,
    UrlV20FromJSON,
    UrlV20FromJSONTyped,
    UrlV20ToJSON,
    WorkContributorsV20,
    WorkContributorsV20FromJSON,
    WorkContributorsV20FromJSONTyped,
    WorkContributorsV20ToJSON,
    WorkTitleV20,
    WorkTitleV20FromJSON,
    WorkTitleV20FromJSONTyped,
    WorkTitleV20ToJSON,
} from './';

/**
 * 
 * @export
 * @interface WorkV20
 */
export interface WorkV20 {
    /**
     * 
     * @type {CreatedDateV20}
     * @memberof WorkV20
     */
    createdDate?: CreatedDateV20;
    /**
     * 
     * @type {LastModifiedDateV20}
     * @memberof WorkV20
     */
    lastModifiedDate?: LastModifiedDateV20;
    /**
     * 
     * @type {SourceV20}
     * @memberof WorkV20
     */
    source?: SourceV20;
    /**
     * 
     * @type {number}
     * @memberof WorkV20
     */
    putCode?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkV20
     */
    path?: string;
    /**
     * 
     * @type {WorkTitleV20}
     * @memberof WorkV20
     */
    title?: WorkTitleV20;
    /**
     * 
     * @type {TitleV20}
     * @memberof WorkV20
     */
    journalTitle?: TitleV20;
    /**
     * 
     * @type {string}
     * @memberof WorkV20
     */
    shortDescription?: string;
    /**
     * 
     * @type {Citation}
     * @memberof WorkV20
     */
    citation?: Citation;
    /**
     * 
     * @type {string}
     * @memberof WorkV20
     */
    type?: WorkV20TypeEnum;
    /**
     * 
     * @type {PublicationDateV20}
     * @memberof WorkV20
     */
    publicationDate?: PublicationDateV20;
    /**
     * 
     * @type {ExternalIDsV20}
     * @memberof WorkV20
     */
    externalIds?: ExternalIDsV20;
    /**
     * 
     * @type {UrlV20}
     * @memberof WorkV20
     */
    url?: UrlV20;
    /**
     * 
     * @type {WorkContributorsV20}
     * @memberof WorkV20
     */
    contributors?: WorkContributorsV20;
    /**
     * 
     * @type {string}
     * @memberof WorkV20
     */
    languageCode?: string;
    /**
     * 
     * @type {CountryV20}
     * @memberof WorkV20
     */
    country?: CountryV20;
    /**
     * 
     * @type {string}
     * @memberof WorkV20
     */
    visibility?: WorkV20VisibilityEnum;
}

/**
* @export
* @enum {string}
*/
export enum WorkV20TypeEnum {
    ArtisticPerformance = 'ARTISTIC_PERFORMANCE',
    BookChapter = 'BOOK_CHAPTER',
    BookReview = 'BOOK_REVIEW',
    Book = 'BOOK',
    ConferenceAbstract = 'CONFERENCE_ABSTRACT',
    ConferencePaper = 'CONFERENCE_PAPER',
    ConferencePoster = 'CONFERENCE_POSTER',
    DataSet = 'DATA_SET',
    DictionaryEntry = 'DICTIONARY_ENTRY',
    Disclosure = 'DISCLOSURE',
    Dissertation = 'DISSERTATION',
    EditedBook = 'EDITED_BOOK',
    EncyclopediaEntry = 'ENCYCLOPEDIA_ENTRY',
    Invention = 'INVENTION',
    JournalArticle = 'JOURNAL_ARTICLE',
    JournalIssue = 'JOURNAL_ISSUE',
    LectureSpeech = 'LECTURE_SPEECH',
    License = 'LICENSE',
    MagazineArticle = 'MAGAZINE_ARTICLE',
    Manual = 'MANUAL',
    NewsletterArticle = 'NEWSLETTER_ARTICLE',
    NewspaperArticle = 'NEWSPAPER_ARTICLE',
    OnlineResource = 'ONLINE_RESOURCE',
    Other = 'OTHER',
    Patent = 'PATENT',
    RegisteredCopyright = 'REGISTERED_COPYRIGHT',
    Report = 'REPORT',
    ResearchTechnique = 'RESEARCH_TECHNIQUE',
    ResearchTool = 'RESEARCH_TOOL',
    SpinOffCompany = 'SPIN_OFF_COMPANY',
    StandardsAndPolicy = 'STANDARDS_AND_POLICY',
    SupervisedStudentPublication = 'SUPERVISED_STUDENT_PUBLICATION',
    TechnicalStandard = 'TECHNICAL_STANDARD',
    Test = 'TEST',
    Trademark = 'TRADEMARK',
    Translation = 'TRANSLATION',
    Website = 'WEBSITE',
    WorkingPaper = 'WORKING_PAPER',
    Undefined = 'UNDEFINED'
}/**
* @export
* @enum {string}
*/
export enum WorkV20VisibilityEnum {
    Limited = 'LIMITED',
    RegisteredOnly = 'REGISTERED_ONLY',
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

export function WorkV20FromJSON(json: any): WorkV20 {
    return WorkV20FromJSONTyped(json, false);
}

export function WorkV20FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkV20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdDate': !exists(json, 'created-date') ? undefined : CreatedDateV20FromJSON(json['created-date']),
        'lastModifiedDate': !exists(json, 'last-modified-date') ? undefined : LastModifiedDateV20FromJSON(json['last-modified-date']),
        'source': !exists(json, 'source') ? undefined : SourceV20FromJSON(json['source']),
        'putCode': !exists(json, 'put-code') ? undefined : json['put-code'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'title': !exists(json, 'title') ? undefined : WorkTitleV20FromJSON(json['title']),
        'journalTitle': !exists(json, 'journal-title') ? undefined : TitleV20FromJSON(json['journal-title']),
        'shortDescription': !exists(json, 'short-description') ? undefined : json['short-description'],
        'citation': !exists(json, 'citation') ? undefined : CitationFromJSON(json['citation']),
        'type': !exists(json, 'type') ? undefined : json['type'],
        'publicationDate': !exists(json, 'publication-date') ? undefined : PublicationDateV20FromJSON(json['publication-date']),
        'externalIds': !exists(json, 'external-ids') ? undefined : ExternalIDsV20FromJSON(json['external-ids']),
        'url': !exists(json, 'url') ? undefined : UrlV20FromJSON(json['url']),
        'contributors': !exists(json, 'contributors') ? undefined : WorkContributorsV20FromJSON(json['contributors']),
        'languageCode': !exists(json, 'language-code') ? undefined : json['language-code'],
        'country': !exists(json, 'country') ? undefined : CountryV20FromJSON(json['country']),
        'visibility': !exists(json, 'visibility') ? undefined : json['visibility'],
    };
}

export function WorkV20ToJSON(value?: WorkV20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created-date': CreatedDateV20ToJSON(value.createdDate),
        'last-modified-date': LastModifiedDateV20ToJSON(value.lastModifiedDate),
        'source': SourceV20ToJSON(value.source),
        'put-code': value.putCode,
        'path': value.path,
        'title': WorkTitleV20ToJSON(value.title),
        'journal-title': TitleV20ToJSON(value.journalTitle),
        'short-description': value.shortDescription,
        'citation': CitationToJSON(value.citation),
        'type': value.type,
        'publication-date': PublicationDateV20ToJSON(value.publicationDate),
        'external-ids': ExternalIDsV20ToJSON(value.externalIds),
        'url': UrlV20ToJSON(value.url),
        'contributors': WorkContributorsV20ToJSON(value.contributors),
        'language-code': value.languageCode,
        'country': CountryV20ToJSON(value.country),
        'visibility': value.visibility,
    };
}


