/* tslint:disable */
/* eslint-disable */
/**
 * ORCID Public
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkBulkV30
 */
export interface WorkBulkV30 {
    /**
     * 
     * @type {Array<object>}
     * @memberof WorkBulkV30
     */
    bulk?: Array<object>;
}

export function WorkBulkV30FromJSON(json: any): WorkBulkV30 {
    return WorkBulkV30FromJSONTyped(json, false);
}

export function WorkBulkV30FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkBulkV30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bulk': !exists(json, 'bulk') ? undefined : json['bulk'],
    };
}

export function WorkBulkV30ToJSON(value?: WorkBulkV30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bulk': value.bulk,
    };
}


