{
  "swagger" : "2.0",
  "info" : {
    "version" : "Latest",
    "title" : "ORCID Public"
  },
  "host" : "pub.orcid.org",
  "tags" : [ {
    "name" : "Identifier API"
  }, {
    "name" : "Public API v2.0"
  }, {
    "name" : "Public API v2.1"
  }, {
    "name" : "Development Public API v3.0"
  }, {
    "name" : "Development Public API v3.0_rc1"
  }, {
    "name" : "Development Public API v3.0_rc2"
  } ],
  "paths" : {
    "/v{version}/identifiers" : {
      "get" : {
        "tags" : [ "Identifier API" ],
        "summary" : "Fetch identifier type map. Defaults to English descriptions",
        "description" : "",
        "operationId" : "viewIdentifierTypes",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.0/status" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Check the server status",
        "description" : "",
        "operationId" : "viewStatusText"
      }
    },
    "/v2.0/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all Activities",
        "description" : "",
        "operationId" : "viewActivities"
      }
    },
    "/v2.0/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviews"
      }
    },
    "/v2.0/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrls"
      }
    },
    "/v2.0/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrl"
      }
    },
    "/v2.0/{orcid}/email" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmails"
      }
    },
    "/v2.0/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetails"
      }
    },
    "/v2.0/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNames"
      }
    },
    "/v2.0/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherName"
      }
    },
    "/v2.0/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiers",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.0/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifier"
      }
    },
    "/v2.0/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywords"
      }
    },
    "/v2.0/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeyword"
      }
    },
    "/v2.0/{orcid}/address" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all addresses",
        "description" : "",
        "operationId" : "viewAddresses"
      }
    },
    "/v2.0/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddress"
      }
    },
    "/v2.0/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiography"
      }
    },
    "/v2.0/{orcid}/person" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPerson"
      }
    },
    "/v2.0/{orcid}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecord"
      }
    },
    "/v2.0/search" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQuery"
      }
    },
    "/v2.0/client/{client_id}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClient"
      }
    },
    "/v2.0/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Work",
        "description" : "More notes about this method",
        "operationId" : "viewWork"
      }
    },
    "/v2.0/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummary"
      }
    },
    "/v2.0/{orcid}/works" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorks"
      }
    },
    "/v2.0/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorks"
      }
    },
    "/v2.0/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFunding"
      }
    },
    "/v2.0/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummary"
      }
    },
    "/v2.0/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundings"
      }
    },
    "/v2.0/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducation"
      }
    },
    "/v2.0/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch an Education Summary",
        "description" : "",
        "operationId" : "viewEducationSummary"
      }
    },
    "/v2.0/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducations"
      }
    },
    "/v2.0/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch an Employment",
        "description" : "Retrive a specific education representation",
        "operationId" : "viewEmployment"
      }
    },
    "/v2.0/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummary"
      }
    },
    "/v2.0/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmployments"
      }
    },
    "/v2.0/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReview"
      }
    },
    "/v2.0/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.0" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummary"
      }
    },
    "/v2.1/status" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Check the server status",
        "description" : "",
        "operationId" : "viewStatusTextV21"
      }
    },
    "/v2.1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all Activities",
        "description" : "",
        "operationId" : "viewActivitiesV21"
      }
    },
    "/v2.1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsV21"
      }
    },
    "/v2.1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsV21"
      }
    },
    "/v2.1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlV21"
      }
    },
    "/v2.1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsV21"
      }
    },
    "/v2.1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsV21"
      }
    },
    "/v2.1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesV21"
      }
    },
    "/v2.1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNameV21"
      }
    },
    "/v2.1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersV21",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierV21"
      }
    },
    "/v2.1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsV21"
      }
    },
    "/v2.1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordV21"
      }
    },
    "/v2.1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all addresses",
        "description" : "",
        "operationId" : "viewAddressesV21"
      }
    },
    "/v2.1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressV21"
      }
    },
    "/v2.1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyV21"
      }
    },
    "/v2.1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonV21"
      }
    },
    "/v2.1/{orcid}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordV21"
      }
    },
    "/v2.1/search" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryV21"
      }
    },
    "/v2.1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientV21"
      }
    },
    "/v2.1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Work",
        "description" : "More notes about this method",
        "operationId" : "viewWorkV21"
      }
    },
    "/v2.1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryV21"
      }
    },
    "/v2.1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksV21"
      }
    },
    "/v2.1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksV21"
      }
    },
    "/v2.1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingV21"
      }
    },
    "/v2.1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryV21"
      }
    },
    "/v2.1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsV21"
      }
    },
    "/v2.1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationV21"
      }
    },
    "/v2.1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch an Education Summary",
        "description" : "",
        "operationId" : "viewEducationSummaryV21"
      }
    },
    "/v2.1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsV21"
      }
    },
    "/v2.1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch an Employment",
        "description" : "Retrive a specific education representation",
        "operationId" : "viewEmploymentV21"
      }
    },
    "/v2.1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryV21"
      }
    },
    "/v2.1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsV21"
      }
    },
    "/v2.1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewV21"
      }
    },
    "/v2.1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Public API v2.1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryV21"
      }
    },
    "/v3.0/status" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Check the server status",
        "description" : "",
        "operationId" : "viewStatusTextv3"
      }
    },
    "/v3.0/pubStatus" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all Activities",
        "description" : "",
        "operationId" : "viewActivitiesv3"
      }
    },
    "/v3.0/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsv3"
      }
    },
    "/v3.0/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsv3"
      }
    },
    "/v3.0/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlv3"
      }
    },
    "/v3.0/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsv3"
      }
    },
    "/v3.0/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsv3"
      }
    },
    "/v3.0/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesv3"
      }
    },
    "/v3.0/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNamev3"
      }
    },
    "/v3.0/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersv3",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierv3"
      }
    },
    "/v3.0/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsv3"
      }
    },
    "/v3.0/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordv3"
      }
    },
    "/v3.0/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all addresses",
        "description" : "",
        "operationId" : "viewAddressesv3"
      }
    },
    "/v3.0/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressv3"
      }
    },
    "/v3.0/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyv3"
      }
    },
    "/v3.0/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonv3"
      }
    },
    "/v3.0/{orcid}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordv3"
      }
    },
    "/v3.0/search" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3"
      }
    },
    "/v3.0/csv-search" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3"
      }
    },
    "/v3.0/expanded-search" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3"
      }
    },
    "/v3.0/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientv3"
      }
    },
    "/v3.0/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Work",
        "description" : "More notes about this method",
        "operationId" : "viewWorkv3"
      }
    },
    "/v3.0/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryv3"
      }
    },
    "/v3.0/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksv3"
      }
    },
    "/v3.0/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksv3"
      }
    },
    "/v3.0/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingv3"
      }
    },
    "/v3.0/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryv3"
      }
    },
    "/v3.0/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsv3"
      }
    },
    "/v3.0/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationv3"
      }
    },
    "/v3.0/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Education Summary",
        "description" : "",
        "operationId" : "viewEducationSummaryv3"
      }
    },
    "/v3.0/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsv3"
      }
    },
    "/v3.0/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Employment",
        "description" : "Retrive a specific education representation",
        "operationId" : "viewEmploymentv3"
      }
    },
    "/v3.0/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryv3"
      }
    },
    "/v3.0/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsv3"
      }
    },
    "/v3.0/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewv3"
      }
    },
    "/v3.0/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryv3"
      }
    },
    "/v3.0/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServicev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourcev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/status" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Check the server status",
        "description" : "",
        "operationId" : "viewStatusTextV3Rc1"
      }
    },
    "/v3.0_rc1/pubStatus" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0_rc1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all Activities",
        "description" : "",
        "operationId" : "viewActivitiesV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNameV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all addresses",
        "description" : "",
        "operationId" : "viewAddressesV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordV3Rc1"
      }
    },
    "/v3.0_rc1/search" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryV3Rc1"
      }
    },
    "/v3.0_rc1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Work",
        "description" : "More notes about this method",
        "operationId" : "viewWorkV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Education Summary",
        "description" : "",
        "operationId" : "viewEducationSummaryV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Employment",
        "description" : "Retrive a specific education representation",
        "operationId" : "viewEmploymentV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryV3Rc1"
      }
    },
    "/v3.0_rc1/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServiceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc1" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/status" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Check the server status",
        "description" : "",
        "operationId" : "viewStatusTextv3Rc2"
      }
    },
    "/v3.0_rc2/pubStatus" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0_rc2/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all Activities",
        "description" : "",
        "operationId" : "viewActivitiesv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNamev3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all addresses",
        "description" : "",
        "operationId" : "viewAddressesv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordv3Rc2"
      }
    },
    "/v3.0_rc2/search" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3Rc2"
      }
    },
    "/v3.0_rc2/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Work",
        "description" : "More notes about this method",
        "operationId" : "viewWorkv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Education Summary",
        "description" : "",
        "operationId" : "viewEducationSummaryv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Employment",
        "description" : "Retrive a specific education representation",
        "operationId" : "viewEmploymentv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryv3Rc2"
      }
    },
    "/v3.0_rc2/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServicev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourcev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Public API v3.0_rc2" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "orcid_two_legs" : {
      "type" : "oauth2",
      "tokenUrl" : "https://pub.orcid.org/oauth/token",
      "flow" : "application",
      "scopes" : {
        "/read-public" : "Read Public record"
      }
    }
  }
}